### ISSUE TITLE
Freeswitch 1.10.6 can't keep running for a long time and often crashes

### ISSUE THREAD

**Issue by luoce** [signalwire/freeswitch#1129]
I use the source code to compile and install, and the client uses webrtc jssip and linphone. It can already call, connect and talk, but after running for a period of time, WSS will disconnect.

When my WSS was unable to connect, I found that the freeswitch service was stopped and had code. * file

freeswitch Version information：
freeswitch@xxxx> version
FreeSWITCH Version 1.10.6-dev+git~20210304T172212Z~e5277a874b~64bit (git e5277a8 2021-03-04 17:22:12Z 64bit)

System version information:
CentOS 7

GBD core file information,It's the same every time:
```
[root@xxx bin]# gdb freeswitch core.32144
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/freeswitch/bin/freeswitch...done.
[New LWP 32386]
[New LWP 32146]
[New LWP 32190]
[New LWP 32182]
[New LWP 32184]
[New LWP 32191]
[New LWP 32209]
[New LWP 32210]
[New LWP 32212]
[New LWP 32186]
[New LWP 32232]
[New LWP 32199]
[New LWP 32211]
[New LWP 32193]
[New LWP 32198]
[New LWP 32192]
[New LWP 32388]
[New LWP 32201]
[New LWP 32181]
[New LWP 32387]
[New LWP 32177]
[New LWP 32144]
[New LWP 32145]
[New LWP 32187]
[New LWP 32178]
[New LWP 32194]
[New LWP 32197]
[New LWP 32203]
[New LWP 32195]
[New LWP 32214]
[New LWP 32202]
[New LWP 32213]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./freeswitch -nc'.
Program terminated with signal 6, Aborted.
#0  0x00007f8263e0d277 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-23.el7.x86_64 flac-libs-1.3.0-5.el7_1.x86_64 glibc-2.17-222.el7.x86_64 gsm-1.0.13-11.el7.x86_64 jbigkit-libs-2.0-11.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-46.el7.x86_64 ldns-1.6.16-10.el7.x86_64 libatomic-4.8.5-44.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libcurl-7.29.0-59.el7_9.1.x86_64 libedit-3.0-12.20121213cvs.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libidn-1.28-4.el7.x86_64 libjpeg-turbo-1.2.90-8.el7.x86_64 libogg-1.3.0-7.el7.x86_64 libselinux-2.5-15.el7.x86_64 libsndfile-1.0.25-12.el7.x86_64 libssh2-1.8.0-4.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 libtiff-4.0.3-35.el7.x86_64 libtool-ltdl-2.4.2-22.el7_3.x86_64 libuuid-2.23.2-65.el7_9.1.x86_64 libvorbis-1.3.3-8.el7.1.x86_64 lua-5.1.4-15.el7.x86_64 mysql-connector-odbc-8.0.23-1.el7.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 nspr-4.19.0-1.el7_5.x86_64 nss-3.36.0-7.el7_5.x86_64 nss-pem-1.0.3-7.el7.x86_64 nss-softokn-3.36.0-5.el7_5.x86_64 nss-softokn-freebl-3.36.0-5.el7_5.x86_64 nss-sysinit-3.36.0-7.el7_5.x86_64 nss-util-3.36.0-1.el7_5.x86_64 openldap-2.4.44-15.el7_5.x86_64 openssl-libs-1.0.2k-21.el7_9.x86_64 opus-1.1-1.el7.centos.x86_64 pcre-8.32-17.el7.x86_64 postgresql-libs-9.2.24-4.el7_8.x86_64 speex-1.2-0.19.rc1.el7.x86_64 sqlite-3.7.17-8.el7_7.1.x86_64 unixODBC-2.3.1-14.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64
(gdb)
(gdb)
(gdb)
(gdb)
(gdb)
(gdb) bt
#0  0x00007f8263e0d277 in raise () from /lib64/libc.so.6
#1  0x00007f8263e0e968 in abort () from /lib64/libc.so.6
#2  0x00007f8263e06096 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f8263e06142 in __assert_fail () from /lib64/libc.so.6
#4  0x00007f82676e7570 in switch_rtp_add_dtls (rtp_session=0x7f8244071e98, local_fp=local_fp@entry=0x7f8238046a18, remote_fp=remote_fp@entry=0x7f8238046b28,
    type=type@entry=(DTLS_TYPE_CLIENT | DTLS_TYPE_RTP | DTLS_TYPE_RTCP), want_DTLSv1_2=want_DTLSv1_2@entry=1 '\001') at src/switch_rtp.c:3794
#5  0x00007f82676a657e in switch_core_media_activate_rtp (session=0x7f82380367e8) at src/switch_core_media.c:8935
#6  0x00007f825d6eee5e in sofia_media_activate_rtp (tech_pvt=tech_pvt@entry=0x7f8238040018) at sofia_media.c:58
#7  0x00007f825d6eeede in sofia_media_tech_media (tech_pvt=tech_pvt@entry=0x7f8238040018,
    r_sdp=r_sdp@entry=0x7f82440190c8 "v=0\r\no=- 4347452372418153829 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS vLQsGO0fwJh7u4ymoiRTKZmZMf9pyv00ykbg\r\nm=audio 52064 UDP/TLS/RTP/SAVPF 111 103 "..., type=type@entry=SDP_TYPE_REQUEST) at sofia_media.c:87
#8  0x00007f825d690d38 in sofia_receive_message (session=0x7f82380367e8, msg=<optimized out>) at mod_sofia.c:2571
#9  0x00007f826767c10b in switch_core_session_perform_receive_message (session=0x7f82380367e8, message=message@entry=0x7f825d59d3b0,
    file=file@entry=0x7f82679ad8f4 "src/switch_ivr_originate.c", func=func@entry=0x7f82679aeba3 <__func__.18818> "setup_ringback", line=line@entry=1275)
    at src/switch_core_session.c:921
#10 0x00007f8267659664 in switch_channel_perform_pre_answer (channel=channel@entry=0x7f823802c950, file=file@entry=0x7f82679ad8f4 "src/switch_ivr_originate.c",
    func=func@entry=0x7f82679aeba3 <__func__.18818> "setup_ringback", line=line@entry=1275) at src/switch_channel.c:3599
#11 0x00007f826770d8a4 in setup_ringback (originate_status=0x7f825d59ea60, originate_status=0x7f825d59ea60, write_codec=0x7f825d59d710, write_frame=0x7f825d59d800,
    ringback=0x7f825d5a0260, ringback_data=0x7f8244018018 "%(2000,4000,440,480)", len=2, oglobals=0x7f825d59e9a0) at src/switch_ivr_originate.c:1275
#12 switch_ivr_originate (session=session@entry=0x7f82380367e8, bleg=bleg@entry=0x7f825d5a5190, cause=cause@entry=0x7f825d5a4ce4, bridgeto=<optimized out>,
    bridgeto@entry=0x7f8244010780 "{^^:sip_invite_domain=172.18.243.219:presence_id=1002@172.18.243.219}sofia/internal/sip:1002@115.193.173.221:49079;transport=tcp,error/user_not_registered", timelimit_sec=timelimit_sec@entry=30, table=table@entry=0x0, cid_name_override=<optimized out>, cid_name_override@entry=0x0,
    cid_num_override=<optimized out>, cid_num_override@entry=0x0, caller_profile_override=caller_profile_override@entry=0x7f8244017cd0, ovars=0x7f8244010610,
    flags=flags@entry=0, cancel_cause=cancel_cause@entry=0x0, dh=dh@entry=0x0) at src/switch_ivr_originate.c:3398
#13 0x00007f822a95c102 in user_outgoing_channel (session=0x7f82380367e8, var_event=0x7f8244010610, outbound_profile=0x7f8244017cd0, new_session=0x7f825d5a5190,
    pool=<optimized out>, flags=<optimized out>, cancel_cause=0x0) at mod_dptools.c:4481
#14 0x00007f826767ca04 in switch_core_session_outgoing_channel (session=0x7f82380367e8, var_event=0x7f8244010610, endpoint_name=endpoint_name@entry=0x7f82440121a0 "user",
    caller_profile=caller_profile@entry=0x7f8244014008, new_session=new_session@entry=0x7f825d5a5190, pool=pool@entry=0x0, flags=flags@entry=0,
    cancel_cause=cancel_cause@entry=0x0) at src/switch_core_session.c:602
#15 0x00007f826770648c in switch_ivr_originate (session=session@entry=0x7f82380367e8, bleg=bleg@entry=0x7f825d5ac7e8, cause=cause@entry=0x7f825d5ac7e0,
    bridgeto=<optimized out>, bridgeto@entry=0x7f82440125b0 "user/1002@172.18.243.219", timelimit_sec=30, timelimit_sec@entry=0, table=table@entry=0x0,
    cid_name_override=cid_name_override@entry=0x0, cid_num_override=cid_num_override@entry=0x0, caller_profile_override=caller_profile_override@entry=0x0,
    ovars=ovars@entry=0x0, flags=flags@entry=0, cancel_cause=cancel_cause@entry=0x0, dh=dh@entry=0x0) at src/switch_ivr_originate.c:2994
#16 0x00007f822a963786 in audio_bridge_function (session=0x7f82380367e8, data=0x7f82440125b0 "user/1002@172.18.243.219") at mod_dptools.c:3630
#17 0x00007f8267680223 in switch_core_session_exec (session=session@entry=0x7f82380367e8, application_interface=application_interface@entry=0x2382920,
    arg=arg@entry=0x7f824400f450 "user/${dialed_extension}@${domain_name}") at src/switch_core_session.c:2891
```

**Comment by andywolk** [comment]
See https://github.com/signalwire/freeswitch/commit/0cab42bfb6284aff2e25c611d0df142a8864ed6f
Should be fixed now. Please try the latest master.
