### ISSUE TITLE
FreeSWITCH Segfault in 1.6 and 1.8

### ISSUE THREAD

**Issue by shaunjstokes** [signalwire/freeswitch#1353]
**Describe the bug**
Segmentation fault occurs on production servers under normal load conditions when a call with call recording ends. We use 'uuid_record' to start call recording and have done for years. This problem is new and has already occurred 4 times in the last week on different servers running different versions of FreeSWITCH (1.6 and 1.8) but there have been no recent changes to our environment.

We also run FreeSWITCH 1.10, upgrading our servers is a work in progress but this problem has already affected multiple servers on different version of FreeSWITCH so for now we have no reason to believe FreeSWITCH 1.10 would be any different.

**To Reproduce**
Not yet able to reproduce.

**Expected behavior**
There should be no segmentation fault.

**Package version or git hash**
 - Version 1.8 and 1.6

**Trace logs**
```
cf8a7195-2f41-467f-b5da-c8bd2214761f 2021-09-23 16:13:48.604080 [DEBUG] switch_ivr_bridge.c:825 sofia/profile3/416@cust1.pbx.example.domain:5555 ending bridge by request from write function
cf8a7195-2f41-467f-b5da-c8bd2214761f 2021-09-23 16:13:48.604080 [DEBUG] switch_ivr_bridge.c:917 BRIDGE THREAD DONE [sofia/profile1/%2B123456@servere01.example.domain:5097]
cf8a7195-2f41-467f-b5da-c8bd2214761f 2021-09-23 16:13:48.604080 [NOTICE] switch_ivr_bridge.c:1034 Hangup sofia/profile1/%2B123456@servere01.example.domain:5097 [CS_EXCHANGE_MEDIA] [NORMAL_CLEARING]
cf8a7195-2f41-467f-b5da-c8bd2214761f 2021-09-23 16:13:48.604080 [DEBUG] mod_hash.c:297 Usage for cust1.pbx.example.domain_bleg_416 is now 0
cf8a7195-2f41-467f-b5da-c8bd2214761f 2021-09-23 16:13:48.604080 [DEBUG] switch_core_state_machine.c:653 (sofia/profile1/%2B123456@servere01.example.domain:5097) State EXCHANGE_MEDIA going to sleep
cf8a7195-2f41-467f-b5da-c8bd2214761f 2021-09-23 16:13:48.604080 [DEBUG] switch_core_state_machine.c:584 (sofia/profile1/%2B123456@servere01.example.domain:5097) Running State Change CS_HANGUP (Cur 98 Tot 83029)
cf8a7195-2f41-467f-b5da-c8bd2214761f 2021-09-23 16:13:48.604080 [DEBUG] switch_ivr_bridge.c:1894 sofia/profile1/%2B123456@servere01.example.domain:5097 skip receive message [UNBRIDGE] (channel is hungup already)
14144078-34f4-477a-9f82-138dabdd468f 2021-09-23 16:13:48.604080 [DEBUG] switch_ivr_bridge.c:1897 sofia/profile3/416@cust1.pbx.example.domain:5555 skip receive message [UNBRIDGE] (channel is hungup already)
cf8a7195-2f41-467f-b5da-c8bd2214761f 2021-09-23 16:13:48.604080 [DEBUG] switch_ivr_async.c:1441 Stop recording file /usr/local/freeswitch/recordings/cust1.pbx.example.domain/archive/2021/Sep/23/cf8a7195-2f41-467f-b5da-c8bd2214761f.mp3
14144078-34f4-477a-9f82-138dabdd468f 2021-09-23 16:13:48.604080 [DEBUG] switch_core_session.c:2905 sofia/profile3/416@cust1.pbx.example.domain:5555 skip receive message [APPLICATION_EXEC_COMPLETE] (channel is hungup already)
14144078-34f4-477a-9f82-138dabdd468f 2021-09-23 16:13:48.604080 [DEBUG] switch_cpp.cpp:1187 sofia/profile3/416@cust1.pbx.example.domain:5555 destroy/unlink session from object
14144078-34f4-477a-9f82-138dabdd468f 2021-09-23 16:13:48.604080 [DEBUG] switch_core_session.c:2905 sofia/profile3/416@cust1.pbx.example.domain:5555 skip receive message [APPLICATION_EXEC_COMPLETE] (channel is hungup already)
14144078-34f4-477a-9f82-138dabdd468f 2021-09-23 16:13:48.604080 [DEBUG] switch_core_state_machine.c:650 (sofia/profile3/416@cust1.pbx.example.domain:5555) State EXECUTE going to sleep
14144078-34f4-477a-9f82-138dabdd468f 2021-09-23 16:13:48.604080 [DEBUG] switch_core_state_machine.c:584 (sofia/profile3/416@cust1.pbx.example.domain:5555) Running State Change CS_HANGUP (Cur 98 Tot 83029)
14144078-34f4-477a-9f82-138dabdd468f 2021-09-23 16:13:48.604080 [DEBUG] switch_core_state_machine.c:847 (sofia/profile3/416@cust1.pbx.example.domain:5555) Callstate Change ACTIVE -> HANGUP
14144078-34f4-477a-9f82-138dabdd468f 2021-09-23 16:13:48.604080 [DEBUG] switch_core_state_machine.c:849 (sofia/profile3/416@cust1.pbx.example.domain:5555) State HANGUP
14144078-34f4-477a-9f82-138dabdd468f 2021-09-23 16:13:48.604080 [DEBUG] mod_sofia.c:460 Channel sofia/profile3/416@cust1.pbx.example.domain:5555 hanging up, cause: NORMAL_CLEARING
2021-09-23 16:13:48.604080 [INFO] mod_shout.c:332 LAME 3.99.5 64bits (http://lame.sf.net)
2021-09-23 16:13:48.604080 [INFO] mod_shout.c:332 polyphase lowpass filter disabled
```

**backtrace from core file**
[backtrace.log](https://github.com/signalwire/freeswitch/files/7220646/backtrace.log)

**Comment by shaunjstokes** [comment]
Here's some snippets of our other backtraces.

The following is on the same server as above using FreeSWITCH 1.8
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1ed039231b in switch_buffer_inuse (buffer=0x0) at src/switch_buffer.c:190
190             return buffer->used;
[Current thread is 1 (Thread 0x7f1cafd9d700 (LWP 28334))]
(gdb) bt
#0  0x00007f1ed039231b in switch_buffer_inuse (buffer=0x0) at src/switch_buffer.c:190
#1  0x00007f1ed048f30f in recording_thread (thread=0x7f1de02cf2b8, obj=0x7f1de02c8e08) at src/switch_ivr_async.c:1267
#2  0x00007f1ed0749747 in dummy_worker (opaque=0x7f1de02cf2b8) at threadproc/unix/thread.c:151
#3  0x00007f1ecf8d94a4 in start_thread (arg=0x7f1cafd9d700) at pthread_create.c:456
#4  0x00007f1eceea5d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) bt full
#0  0x00007f1ed039231b in switch_buffer_inuse (buffer=0x0) at src/switch_buffer.c:190
No locals.
#1  0x00007f1ed048f30f in recording_thread (thread=0x7f1de02cf2b8, obj=0x7f1de02c8e08) at src/switch_ivr_async.c:1267
        bug = 0x7f1de02c8e08
        session = 0x7f1cb838e428
        channel = 0x7f1cb8087570
        rh = 0x7f1de0123b38
        bsize = 8192
        samples = 4096
        inuse = 3264
        data = 0x7f1e000c9868 "\337\377\017"
        channels = 1
        read_impl = {codec_type = SWITCH_CODEC_TYPE_AUDIO, ianacode = 0 '\000', iananame = 0x0, fmtp = 0x0, samples_per_second = 0, actual_samples_per_second = 0, bits_per_second = 0, microseconds_per_packet = 0, samples_per_packet = 0,
          decoded_bytes_per_packet = 0, encoded_bytes_per_packet = 0, number_of_channels = 0 '\000', codec_frames_per_packet = 0, init = 0x0, encode = 0x0, decode = 0x0, encode_video = 0x0, decode_video = 0x0, codec_control = 0x0, destroy = 0x0, codec_id = 0,
          impl_id = 0, modname = 0x0, next = 0x0}
        __func__ = "recording_thread"
#2  0x00007f1ed0749747 in dummy_worker (opaque=0x7f1de02cf2b8) at threadproc/unix/thread.c:151
        thread = 0x7f1de02cf2b8
#3  0x00007f1ecf8d94a4 in start_thread (arg=0x7f1cafd9d700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7f1cafd9d700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139761186100992, 1370225156135481212, 139761170304606, 139761170304607, 139761185853440, 3, -1351824023230451844, -1352879109518626948}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {
              prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#4  0x00007f1eceea5d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.
(gdb)
```

The following are on FreeSWITCH 1.6
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe36556d31b in switch_buffer_inuse (buffer=0x0) at src/switch_buffer.c:190
190             return buffer->used;
[Current thread is 1 (Thread 0x7fe23696f700 (LWP 30960))]
(gdb) bt
#0  0x00007fe36556d31b in switch_buffer_inuse (buffer=0x0) at src/switch_buffer.c:190
#1  0x00007fe36566a30f in recording_thread (thread=0x7fe0ac132c80, obj=0x7fe0ac12c7c8) at src/switch_ivr_async.c:1267
#2  0x00007fe365924747 in dummy_worker (opaque=0x7fe0ac132c80) at threadproc/unix/thread.c:151
#3  0x00007fe364ab44a4 in start_thread (arg=0x7fe23696f700) at pthread_create.c:456
#4  0x00007fe364080d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) bt full
#0  0x00007fe36556d31b in switch_buffer_inuse (buffer=0x0) at src/switch_buffer.c:190
No locals.
#1  0x00007fe36566a30f in recording_thread (thread=0x7fe0ac132c80, obj=0x7fe0ac12c7c8) at src/switch_ivr_async.c:1267
        bug = 0x7fe0ac12c7c8
        session = 0x7fe3243e8d78
        channel = 0x7fe3240827a0
        rh = 0x7fe0ac02b7a8
        bsize = 8192
        samples = 4096
        inuse = 6208
        data = 0x7fe0800b7638 "\n"
        channels = 1
        read_impl = {codec_type = SWITCH_CODEC_TYPE_AUDIO, ianacode = 0 '\000', iananame = 0x0, fmtp = 0x0, samples_per_second = 0, actual_samples_per_second = 0, bits_per_second = 0, microseconds_per_packet = 0, samples_per_packet = 0,
          decoded_bytes_per_packet = 0, encoded_bytes_per_packet = 0, number_of_channels = 0 '\000', codec_frames_per_packet = 0, init = 0x0, encode = 0x0, decode = 0x0, encode_video = 0x0, decode_video = 0x0, codec_control = 0x0,
          destroy = 0x0, codec_id = 0, impl_id = 0, modname = 0x0, next = 0x0}
        __func__ = "recording_thread"
#2  0x00007fe365924747 in dummy_worker (opaque=0x7fe0ac132c80) at threadproc/unix/thread.c:151
        thread = 0x7fe0ac132c80
#3  0x00007fe364ab44a4 in start_thread (arg=0x7fe23696f700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7fe23696f700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140609555199744, 6108376230484749189, 140609558200734, 140609558200735, 140609554952192, 3, -6124575549546583163, -6123903150079235195}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0,
              0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#4  0x00007fe364080d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.
(gdb)
```
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f51b251d31b in switch_buffer_inuse (buffer=0x0) at src/switch_buffer.c:190
190             return buffer->used;
[Current thread is 1 (Thread 0x7f4f6de4c700 (LWP 22304))]
(gdb)
(gdb) bt
#0  0x00007f51b251d31b in switch_buffer_inuse (buffer=0x0) at src/switch_buffer.c:190
#1  0x00007f51b261a30f in recording_thread (thread=0x7f4f900d9b88, obj=0x7f4f900d36d8) at src/switch_ivr_async.c:1267
#2  0x00007f51b28d4747 in dummy_worker (opaque=0x7f4f900d9b88) at threadproc/unix/thread.c:151
#3  0x00007f51b1a644a4 in start_thread (arg=0x7f4f6de4c700) at pthread_create.c:456
#4  0x00007f51b1030d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) bt full
#0  0x00007f51b251d31b in switch_buffer_inuse (buffer=0x0) at src/switch_buffer.c:190
No locals.
#1  0x00007f51b261a30f in recording_thread (thread=0x7f4f900d9b88, obj=0x7f4f900d36d8) at src/switch_ivr_async.c:1267
        bug = 0x7f4f900d36d8
        session = 0x7f4fcc1eed08
        channel = 0x7f4fcc0b3830
        rh = 0x7f4f900a7528
        bsize = 8192
        samples = 4096
        inuse = 1728
        data = 0x7f4f48095818 "/"
        channels = 1
        read_impl = {codec_type = SWITCH_CODEC_TYPE_AUDIO, ianacode = 0 '\000', iananame = 0x0, fmtp = 0x0, samples_per_second = 0, actual_samples_per_second = 0, bits_per_second = 0, microseconds_per_packet = 0,
          samples_per_packet = 0, decoded_bytes_per_packet = 0, encoded_bytes_per_packet = 0, number_of_channels = 0 '\000', codec_frames_per_packet = 0, init = 0x0, encode = 0x0, decode = 0x0, encode_video = 0x0,
          decode_video = 0x0, codec_control = 0x0, destroy = 0x0, codec_id = 0, impl_id = 0, modname = 0x0, next = 0x0}
        __func__ = "recording_thread"
#2  0x00007f51b28d4747 in dummy_worker (opaque=0x7f4f900d9b88) at threadproc/unix/thread.c:151
        thread = 0x7f4f900d9b88
#3  0x00007f51b1a644a4 in start_thread (arg=0x7f4f6de4c700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7f4f6de4c700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139979122853632, 1276066762389077149, 139979128344158, 139979128344159, 139979122606080, 3, -1212695093339603811, -1218755067571061603}, mask_was_saved = 0}}, priv = {pad = {
              0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#4  0x00007f51b1030d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
No locals.
(gdb)
```

We would appreciate any help in troubleshooting this further, I've compared the 'recording_thread' function in 'switch_ivr_async.c' between 1.6, 1.8 and 1.10 but there isn't a lot of difference and for now the cause is eluding us.

**Comment by crienzo** [comment]
Try to crash it in 1.10 and provide trace.
