### ISSUE TITLE
Freeswitch crashed accidentally

### ISSUE THREAD

**Issue by xlb0479** [signalwire/freeswitch#1569]
**Describe the bug**

Freeswitch 1.10.5

My Freeswitch just crashed accidentally.

This is the dump info.

Need help to find out what is the problem.

Thanks.

![image](https://user-images.githubusercontent.com/11763303/157375479-1c9118e6-b64f-47bd-80cb-0a520cc99407.png)

**Comment by seven1240** [comment]
1. try latest master
2. if still has problem, post log `bt full`, logs better in text formatted as code blocks than attached image.

**Comment by xlb0479** [comment]
@seven1240 
Thanks for the reply.

While upgrade to the master is not yet an option to my team.
I just post the `bt full` log here.

Can you help me to figure this out?
Thanks.
```
(gdb) bt full
#0  0x00007fb3008fb901 in __strlen_sse2_pminub () at ../sysdeps/x86_64/multiarch/strlen-sse2-pminub.S:216
No locals.
#1  0x00007fb302012bfd in apr_vformatter (flush_func=flush_func@entry=0x7fb3020112f0 <snprintf_flush>, vbuff=vbuff@entry=0x7fb29995fb80, fmt=0x7fb29b361e49 "s> [%d]", ap=0x7fb299960bf8)
    at strings/apr_snprintf.c:978
        print_something = YES
        sp = 0x7fb29995fbdc ""
        bep = 0x7fb299960bbf ""
        cc = <optimized out>
        i = <optimized out>
        s = 0x40000000a <Address 0x40000000a out of bounds>
        q = <optimized out>
        s_len = <optimized out>
        min_width = <optimized out>
        precision = 0
        adjust = RIGHT
        pad_char = <optimized out>
        prefix_char = 0 '\000'
        fp_num = <optimized out>
        i_quad = <optimized out>
        ui_quad = <optimized out>
        i_num = 0
        ui_num = <optimized out>
        num_buf = "\377\377\377\377\000\000\000\000N\376\000\002\263\177\000\000\330\000\000\000\000\000\000\000\000v\004\214\262\177", '\000' <repeats 11 times>, "v\004\214\262\177\000\000Ȏ\322\372\262\177\000\000[\362\316\001\263\177", '\000' <repeats 11 times>, "v\004\214\262\177\000\000\a\000\000\000\000\000\000\000\364\261\335\001\263\177\000\000\366\000\000\000\064\062\000\000\200\000\000\000\262\177\000\000\362\353\065\233\262\177\000\000\031y\006\000\000\000\000\000\370:\r\214\262\177\000\000\216y7\233\366\000\000\000\031\035\264\276\070\331\005\000\030\373\225\231\262\177\000\000\350\003\000\000\262\177\000\000@\372\225\231\262\177\000\000\000\000\000\000\000\000\000\000d\000\000\000\000\000\000\000\350\372\225\231\262\177\000\000\000\000\000\000\000\000\000\000"...
        char_buf = "\000"
        var_type = <optimized out>
        alternate_form = <optimized out>
        print_sign = <optimized out>
        print_blank = NO
        adjust_precision = (unknown: 10)
        adjust_width = NO
        is_negative = 0
#2  0x00007fb3020137b0 in apr_vsnprintf (buf=buf@entry=0x7fb29995fbc0 "Cancel MRCP Request <(null)@", len=len@entry=4096, format=<optimized out>, ap=<optimized out>) at strings/apr_snprintf.c:1363
        cc = <optimized out>
        vbuff = {curpos = 0x7fb29995fbc0 "Cancel MRCP Request <(null)@", endpos = 0x7fb299960bbf ""}
#3  0x00007fb29b260604 in unimrcp_log (file=0x7fb29b3620a1 "src/mrcp_client_connection.c", line=477, obj=<optimized out>, priority=<optimized out>, format=<optimized out>, arg_ptr=<optimized out>)
    at mod_unimrcp.c:4565
        level = SWITCH_LOG_WARNING
        log_message = "Cancel MRCP Request <(null)@", '\000' <repeats 4067 times>
        msglen = <optimized out>
        id = 0x7fb1842e5d10 "ASR-30242"
#4  0x00007fb29b27b01c in apt_obj_log (file=file@entry=0x7fb29b3620a1 "src/mrcp_client_connection.c", line=line@entry=477, priority=priority@entry=APT_PRIO_WARNING, obj=<optimized out>,
    format=format@entry=0x7fb29b361e30 "Cancel MRCP Request <%s@%s> [%d]") at src/apt_log.c:449
        arg_ptr = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fb299960cd8, reg_save_area = 0x7fb299960c10}}
        status = 1
#5  0x00007fb29b26ebb7 in mrcp_client_agent_request_cancel (channel=0x7fb1842e78e8, message=0x7fb1842f3f30, agent=<optimized out>) at src/mrcp_client_connection.c:477
        response = <optimized out>
#6  0x00007fb29b26f43d in mrcp_client_timer_proc (timer=<optimized out>, obj=0x7fb1842e78e8) at src/mrcp_client_connection.c:692
        timer = <optimized out>
        obj = 0x7fb1842e78e8
        channel = 0x7fb1842e78e8
#7  0x00007fb29b27e67a in apt_timer_queue_advance (timer_queue=0x2309180, elapsed_time=<optimized out>) at src/apt_timer_queue.c:106
        timer = <optimized out>
#8  0x00007fb29b27b8e8 in apt_poller_task_run (base=<optimized out>) at src/apt_poller_task.c:276
        task = 0x2307130
        running = 0x23090d8
        status = <optimized out>
        timeout = 2957000
        queue_timeout = 2957
        time_now = <optimized out>
        time_last = 1646212624434327
---Type <return> to continue, or q <return> to quit---
        task_name = 0x7fb29b35efb9 "MRCPv2ConnectionAgent"
#9  0x00007fb29b27c257 in apt_task_run (thread_handle=0x231b7a8, data=0x2308fe8) at src/apt_task.c:591
        task = 0x2308fe8
#10 0x00007fb30201e9a0 in dummy_worker (opaque=0x231b7a8) at threadproc/unix/thread.c:151
        thread = 0x231b7a8
#11 0x00007fb301235dd5 in __nptl_deallocate_tsd () at pthread_create.c:171
        cnt = 0
#12 0x00007fb299961700 in ?? ()
No symbol table info available.
#13 0x1f10df189530b412 in ?? ()
No symbol table info available.
#14 0x1f13ee7235cab412 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by dragos-oancea** [comment]
perhaps try new mrcp lib ? https://github.com/signalwire/freeswitch/pull/1071 - try this, you will have to rebase that branch with master probably.

**Comment by xlb0479** [comment]
Thanks for the reply.

**Comment by ManManQingLuoMc** [comment]
I am faced with the same problem .
