### ISSUE TITLE
Large conference layout crashes FreeSWITCH

### ISSUE THREAD

**Issue by thehunmonkgroup** [signalwire/freeswitch#16]
Ported from Jira: https://freeswitch.org/jira/browse/FS-12003

Attempting to load test FreeSWITCH mux'd videoconference, I used the attached conference_layouts.conf.xml with a rather robust 121 image slots in the layout.

When the dialplan calls a conference with this layout, FreeSWITCH crashes with the attached backtrace.

[conference_layouts.conf.xml.txt](https://github.com/signalwire/freeswitch/files/3655214/conference_layouts.conf.xml.txt)

[freeswitch-conference-bug-backtrace.txt](https://github.com/signalwire/freeswitch/files/3655212/freeswitch-conference-bug-backtrace.txt)

**Comment by seven1240** [comment]
can you print the `img` and `*img` in frame 4 ?

**Comment by thehunmonkgroup** [comment]
@seven1240 I'll need a little guidance here. Do you want me to add a debugging line just above line 302 of ```src/switch_core_video.c```? If so, what exactly do you want me to add?

**Comment by mjerris** [comment]
in gdb for this core
frame 4
print img
print *img

**Comment by thehunmonkgroup** [comment]
```gdb
(gdb) frame 4
#4  0x00007f1d7c1d1e3f in switch_img_free (img=img@entry=0x7f1d1c098d00) at src/switch_core_video.c:302
302			switch_assert((*img)->fmt <= SWITCH_IMG_FMT_I44016);
(gdb) print img
$1 = (switch_image_t **) 0x7f1d1c098d00
(gdb) print *img
$2 = (switch_image_t *) 0x7f1d1c077918
(gdb)
```

Let me know if you need anything else.

**Comment by mjerris** [comment]
sorry.. need print **img

**Comment by thehunmonkgroup** [comment]
```gdb
(gdb) frame 4
#4  0x00007f1d7c1d1e3f in switch_img_free (img=img@entry=0x7f1d1c098d00) at src/switch_core_video.c:302
302			switch_assert((*img)->fmt <= SWITCH_IMG_FMT_I44016);
(gdb) print **img
$1 = {fmt = 470259120, cs = 32541, range = (unknown: 470259920), w = 32541, h = 470259784, bit_depth = 32541, 
  d_w = 470259824, d_h = 32541, r_w = 470259888, r_h = 32541, x_chroma_shift = 470259856, y_chroma_shift = 32541, 
  planes = {0x0, 0x7f1d1c078080 "soft", 0x0, 0x0}, stride = {0, 0, 0, 0}, bps = 0, user_priv = 0x0, img_data = 0x0, 
  img_data_owner = 0, self_allocd = 0, fb_priv = 0x0}
(gdb)
```
