### ISSUE TITLE
crash in audio call

### ISSUE THREAD

**Issue by 13823520301** [signalwire/freeswitch#1671]
Hello,

**Describe the bug**
FreeSwitch install by source compile on Centos7.9, then run the program package of freeswitch, but crash when to voice call.

**To Reproduce**
1. Using this default configuration...
2. Dial into conference using sip
3. Test a audio call
4. FreeSWITCH crashes

**Package version or git hash**
 - Version [e.g. 1.10.7]

**Trace logs**
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_rtp.c:4619 Starting timer [soft] 160 bytes per 20ms
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_core_media.c:8997 Activating RTCP PORT 4001
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_rtp.c:5017 RTCP send rate is: 1000 and packet rate is: 20000 Remote Port: 4001
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_rtp.c:2776 Setting RTCP remote addr to 192.168.1.12:4001 2
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_core_media.c:9089 sofia/internal/1001@192.168.1.12:56979 Set 2833 dtmf send payload to 101
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_core_media.c:9096 sofia/internal/1001@192.168.1.12:56979 Set 2833 dtmf receive payload to 101
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_core_media.c:9119 sofia/internal/1001@192.168.1.12:56979 Set rtp dtmf delay to 40
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [NOTICE] sofia.c:8683 Channel [sofia/internal/1001@192.168.1.12:56979] has been answered
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_channel.c:3950 (sofia/internal/1001@192.168.1.12:56979) Callstate Change RINGING -> ACTIVE
8b0959e0-dca7-11ec-b27c-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_core_codec.c:248 sofia/internal/1000@192.168.1.171 Restore previous codec PCMA:8.
8b0959e0-dca7-11ec-b27c-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_core_media.c:8759 Audio params are unchanged for sofia/internal/1000@192.168.1.171.
8b0959e0-dca7-11ec-b27c-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] mod_sofia.c:913 Local SDP sofia/internal/1000@192.168.1.171:
8b0959e0-dca7-11ec-b27c-5541bbeb5974 v=0
8b0959e0-dca7-11ec-b27c-5541bbeb5974 o=FreeSWITCH 1653520922 1653520924 IN IP4 192.168.1.171
8b0959e0-dca7-11ec-b27c-5541bbeb5974 s=FreeSWITCH
8b0959e0-dca7-11ec-b27c-5541bbeb5974 c=IN IP4 192.168.1.171
8b0959e0-dca7-11ec-b27c-5541bbeb5974 t=0 0
8b0959e0-dca7-11ec-b27c-5541bbeb5974 m=audio 16402 RTP/AVP 8 101
8b0959e0-dca7-11ec-b27c-5541bbeb5974 a=rtpmap:8 PCMA/8000
8b0959e0-dca7-11ec-b27c-5541bbeb5974 a=rtpmap:101 telephone-event/8000
8b0959e0-dca7-11ec-b27c-5541bbeb5974 a=fmtp:101 0-15
8b0959e0-dca7-11ec-b27c-5541bbeb5974 a=ptime:20
8b0959e0-dca7-11ec-b27c-5541bbeb5974 a=sendrecv
8b0959e0-dca7-11ec-b27c-5541bbeb5974 a=rtcp:16403 IN IP4 192.168.1.171
8b0959e0-dca7-11ec-b27c-5541bbeb5974 
8b0959e0-dca7-11ec-b27c-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [NOTICE] switch_ivr_originate.c:3834 Channel [sofia/internal/1000@192.168.1.171] has been answered
8b0959e0-dca7-11ec-b27c-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_channel.c:3950 (sofia/internal/1000@192.168.1.171) Callstate Change EARLY -> ACTIVE
8b0959e0-dca7-11ec-b27c-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] sofia.c:7499 Channel sofia/internal/1000@192.168.1.171 entering state [completed][200]
8b0959e0-dca7-11ec-b27c-5541bbeb5974 2022-05-26 11:55:33.450016 99.90% [DEBUG] switch_ivr_originate.c:3892 Originate Resulted in Success: [sofia/internal/1001@192.168.1.12:56979] Peer UUID: abdf3ea0-dca7-11ec-b2a0-5541bbeb5974
8b0959e0-dca7-11ec-b27c-5541bbeb5974 2022-05-26 11:55:33.469967 99.90% [DEBUG] switch_ivr_originate.c:3892 Originate Resulted in Success: [sofia/internal/1001@192.168.1.12:56979] Peer UUID: abdf3ea0-dca7-11ec-b2a0-5541bbeb5974
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.469967 99.90% [DEBUG] switch_ivr_bridge.c:1793 (sofia/internal/1001@192.168.1.12:56979) State Change CS_CONSUME_MEDIA -> CS_EXCHANGE_MEDIA
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.469967 99.90% [DEBUG] switch_core_state_machine.c:581 (sofia/internal/1001@192.168.1.12:56979) Running State Change CS_EXCHANGE_MEDIA (Cur 2 Tot 2)
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.469967 99.90% [DEBUG] switch_core_state_machine.c:650 (sofia/internal/1001@192.168.1.12:56979) State EXCHANGE_MEDIA
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.469967 99.90% [DEBUG] mod_sofia.c:671 SOFIA EXCHANGE_MEDIA
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.490693 99.90% [DEBUG] switch_rtp.c:1982 rtcp_stats_init: audio ssrc[1231234737] base_seq[19598]
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.510029 99.90% [DEBUG] switch_rtp.c:7934 Correct audio ip/port confirmed.
8b0959e0-dca7-11ec-b27c-5541bbeb5974 2022-05-26 11:55:33.510029 99.90% [DEBUG] switch_rtp.c:7934 Correct audio ip/port confirmed.
abdf3ea0-dca7-11ec-b2a0-5541bbeb5974 2022-05-26 11:55:33.709996 99.90% [DEBUG] switch_rtp.c:7331 Correct audio RTCP ip/port confirmed.
8b0959e0-dca7-11ec-b27c-5541bbeb5974 2022-05-26 11:55:35.230014 99.83% [DEBUG] switch_rtp.c:7331 Correct audio RTCP ip/port confirmed.

**backtrace from core file**
(gdb) bt
#0  0x00007fecb668e1b0 in wcslen () from /usr/lib64/libc.so.6
#1  0x00007fecb668f72c in wcsrtombs () from /usr/lib64/libc.so.6
#2  0x00007fecb66319da in vfprintf () from /usr/lib64/libc.so.6
#3  0x00007fecb665de73 in vasprintf () from /usr/lib64/libc.so.6
#4  0x00007fecb9e60d5c in switch_vasprintf (ret=0x7fec6c029300, fmt=0x7fec645d3010 "{\n\t\"listen"..., ap=0x7fec6c029308) at src/switch_apr.c:1268
#5  0x00007fecb0619865 in http_stream_write (handle=<optimized out>, fmt=<optimized out>) at mod_xml_rpc.c:197
#6  0x00007fecabdf8ff1 in event_sink_function (cmd=<optimized out>, session=<optimized out>, stream=0x7fec6c029560) at mod_event_socket.c:1126
#7  0x00007fecb9f2b5e5 in switch_api_execute (cmd=0x1283125 "event_sink", arg=0x11373b0 "command=ch"..., session=0x0, stream=0x7fec6c029560) at src/switch_loadable_module.c:2963
#8  0x00007fecb06196c8 in handler_hook (r=0x7fec6c02b740) at mod_xml_rpc.c:1079
#9  0x00007fecb0626750 in runUserHandler (srvP=0x7fec24043040, sessionP=0x7fec6c02b740) at ../../../../libs/xmlrpc-c/lib/abyss/src/server.c:573
#10 processRequestFromClient (connectionP=connectionP@entry=0x7fec2410aad0, lastReqOnConn=<optimized out>, timeout=<optimized out>, keepAliveP=keepAliveP@entry=0x7fec6c02b894)
    at ../../../../libs/xmlrpc-c/lib/abyss/src/server.c:661
#11 0x00007fecb06268b5 in serverFunc (userHandle=0x7fec2410aad0) at ../../../../libs/xmlrpc-c/lib/abyss/src/server.c:727
#12 0x00007fecb061d117 in connJob (userHandle=0x7fec2410aad0) at ../../../../libs/xmlrpc-c/lib/abyss/src/conn.c:39
#13 0x00007fecb062a90b in pthreadStart (arg=0x7fec2404d6b0) at ../../../../libs/xmlrpc-c/lib/abyss/src/thread_pthread.c:49
#14 0x00007fecb7090ea5 in start_thread () from /usr/lib64/libpthread.so.0
#15 0x00007fecb66e4b0d in clone () from /usr/lib64/libc.so.6

please help ,thank you!

**Comment by bit4bit** [comment]
hi @13823520301 can you paste the dialplan?
