### ISSUE TITLE
Crash bug with enterprise originate

### ISSUE THREAD

**Issue by leedm777** [signalwire/freeswitch#1880]
**Describe the bug**
Enterprise originate occasionally crashes when one of the child originations fail.

I dug into it a big, and it appears to be a problem with how threads are handled within enterprise originate. In `enterprise_originate_thread`, there's quite a bit of data that's written to what `handle` points to without locking a mutex or anything that would act like a [memory fence](https://stackoverflow.com/a/286705/115478). This means those writes might not happen in the order expected when `switch_ivr_enterprise_originate` reads from `handle`. That creates a race condition where it's possible that the call fails, `handle->done` is set to `1`, but from the parent thread still sees `handle->status` as 0, which is `SWITCH_STATUS_SUCCESS`. This makes it look like the call succeeded, when actually the failed status hasn't been written yet.

**To Reproduce**
1. Configure an extension to use enterprise originate to a destination that rejects the call.
```
    <extension name="breakit">
      <condition field="destination_number" expression="^999$">
        <action application="bridge" data="<originate_timeout=54,no_throttle_limits=true,ignore_early_media=true,fail_on_single_reject=!^^:GATEWAY_DOWN:ORIGINATOR_CANCEL:NORMAL_CLEARING:UNALLOCATED_NUMBER>{leg_timeout=54}sofia/gateway/sip2-noop/group_11795123|loopback/250/sleep|sofia/gateway/sip1-noop2/group_11795123|loopback/250/sleep|sofia/gateway/sip1-noop/group_11795123|loopback/493573/setoffline:_:"/>
      </condition>
    </extension>
```
3. Use something like sipp to bulk dial that extension
4. Wait. Within a day or two FreeSWITCH should crash.

**Expected behavior**
Calls should be cleanly rejected without a crash

**Package version or git hash**
 - 1.10.7

**Trace logs**
None

**backtrace from core file**
If applicable, provide the full backtrace from the core file.
```
#0  switch_core_session_get_channel (session=0x0) at src/switch_core_session.c:1441
#1  0x00007f5360082f91 in audio_bridge_function (session=0x7f5344fecd18, 
    data=0x7f502c13ac80 "<originate_timeout=30,no_throttle_limits=true,ignore_early_media=true,fail_on_single_reject=!^^:GATEWAY_DOWN:ORIGINATOR_CANCEL:NORMAL_CLEARING:UNALLOCATED_NUMBER>{sip_"...)
    at mod_dptools.c:3662
#2  0x00007f53650076cf in switch_core_session_exec (session=session@entry=0x7f5344fecd18, application_interface=application_interface@entry=0x5646b272f878, 
    arg=arg@entry=0x7f502c12db28 "<originate_timeout=${call_timeout},no_throttle_limits=true,ignore_early_media=true,fail_on_single_reject=!^^:GATEWAY_DOWN:ORIGINATOR_CANCEL:NORMAL_CLEARING:UNALLOCATED_NUMBER>${destination_number}:_:")
    at src/switch_core_session.c:2969
#3  0x00007f5365007e6f in switch_core_session_execute_application_get_flags (session=session@entry=0x7f5344fecd18, app=0x7f502c12db20 "bridge", 
    arg=0x7f502c12db28 "<originate_timeout=${call_timeout},no_throttle_limits=true,ignore_early_media=true,fail_on_single_reject=!^^:GATEWAY_DOWN:ORIGINATOR_CANCEL:NORMAL_CLEARING:UNALLOCATED_NUMBER>${destination_number}:_:", 
    flags=flags@entry=0x0) at src/switch_core_session.c:2829
#4  0x00007f536500876f in switch_core_session_execute_exten (session=0x7f5344fecd18, exten=<optimized out>, dialplan=<optimized out>, context=<optimized out>) at src/switch_core_session.c:3099
#5  0x00007f536007961f in exe_function (session=0x7f5344fecd18, 
    data=0x7f502c13c718 "{presence_id=4906@xxxx,call_timeout=30"...)
    at mod_dptools.c:659
#6  0x00007f53650076cf in switch_core_session_exec (session=session@entry=0x7f5344fecd18, application_interface=application_interface@entry=0x5646b272c360, 
    arg=arg@entry=0x7f502c13c718 "{presence_id=4906@xxxxcall_timeout=30"...) at src/switch_core_session.c:2969
#7  0x00007f5365007e6f in switch_core_session_execute_application_get_flags (session=session@entry=0x7f5344fecd18, app=0x7f502c11f028 "execute_extension", 
    arg=0x7f502c13c718 "{presence_id=4906@xxxx,call_timeout=30"..., 
    flags=flags@entry=0x0) at src/switch_core_session.c:2829
#8  0x00007f536500c1d2 in switch_core_standard_on_execute (session=0x7f5344fecd18) at src/switch_core_state_machine.c:350
#9  switch_core_session_run (session=0x7f5344fecd18) at src/switch_core_state_machine.c:647
#10 0x00007f536500504e in switch_core_session_thread (thread=<optimized out>, obj=0x7f5344fecd18) at src/switch_core_session.c:1736
#11 0x00007f53650007ab in switch_core_session_thread_pool_worker (thread=0x7f50280a0100, obj=<optimized out>) at src/switch_core_session.c:1800
#12 0x00007f53651539ac in dummy_worker (opaque=0x7f50280a0100) at threadproc/unix/thread.c:151
#13 0x00007f5364f0ffa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#14 0x00007f5364ac54cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by andywolk** [comment]
Thank you David for your report! Please take a look at this PR https://github.com/signalwire/freeswitch/pull/1881

**Comment by leedm777** [comment]
@andywolk, thanks for the quick response. Looks like that probably fixes the issue. Let me try that out and see if things are less crashy.

**Comment by andywolk** [comment]
@leedm777 How is it going?

**Comment by leedm777** [comment]
@andywolk So far, so good. It’s been about two days with no crash. I’ll let it run over the weekend and check back in with you on Monday.

**Comment by leedm777** [comment]
@andywolk Test ran all weekend without a crash. LGTM!

**Comment by andywolk** [comment]
Thank you for testing that! Merged.
