### ISSUE TITLE
Segfault after playing audio to a conference member

### ISSUE THREAD

**Issue by two56** [signalwire/freeswitch#1939]
Using drachtio (jambonz) to control FreeSWITCH, FreeSWITCH segfaults after playing audio to a conference member when re-entering the conference.

I believe these are the steps jambonz is executing:
1. Command Execute conference(...) 
2. Queue a file to play
3. Command Execute conference(...)

Expected behaviour
The member to re-enter the conference when the second conference command is executed.

Version
 - 1.10.5-release+git~20200818T185121Z~25569c1631~64bit

Logs
```
2de1572e-17e3-4b9b-8856-60a8b13e097d EXECUTE [depth=1] sofia/drachtio_mrf/nobody@172.25.0.166:5060 answer()
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.043085 [DEBUG] switch_ivr.c:632 sofia/drachtio_mrf/nobody@172.25.0.166:5060 Command Execute [depth=1] set(hangup_after_bridge=false)
2de1572e-17e3-4b9b-8856-60a8b13e097d EXECUTE [depth=1] sofia/drachtio_mrf/nobody@172.25.0.166:5060 set(hangup_after_bridge=false)
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.043085 [DEBUG] mod_dptools.c:1672 SET sofia/drachtio_mrf/nobody@172.25.0.166:5060 [hangup_after_bridge]=[false]
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.043085 [DEBUG] switch_ivr.c:632 sofia/drachtio_mrf/nobody@172.25.0.166:5060 Command Execute [depth=1] set(park_after_bridge=true)
2de1572e-17e3-4b9b-8856-60a8b13e097d EXECUTE [depth=1] sofia/drachtio_mrf/nobody@172.25.0.166:5060 set(park_after_bridge=true)
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.043085 [DEBUG] mod_dptools.c:1672 SET sofia/drachtio_mrf/nobody@172.25.0.166:5060 [park_after_bridge]=[true]
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.083089 [DEBUG] switch_ivr.c:632 sofia/drachtio_mrf/nobody@172.25.0.166:5060 Command Execute [depth=1] conference(conf:bc3f20fd-7a57-49f7-90c6-caacbe4121ac:conference)
2de1572e-17e3-4b9b-8856-60a8b13e097d EXECUTE [depth=1] sofia/drachtio_mrf/nobody@172.25.0.166:5060 conference(conf:bc3f20fd-7a57-49f7-90c6-caacbe4121ac:conference)
2022-12-12 12:19:44.083089 [DEBUG] mod_conference.c:3414 using channel sound prefix: /usr/local/freeswitch/sounds/en/us/callie
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:1764 Raw Codec Activation Success L16@8000hz 1 channel 20ms
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:1811 Raw Codec Activation Success L16@8000hz 1 channel 20ms
2022-12-12 12:19:44.083089 [DEBUG] mod_conference.c:228 Setup timer success interval: 20  samples: 160
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.083089 [DEBUG] switch_core_codec.c:223 sofia/drachtio_mrf/nobody@172.25.0.166:5060 Push codec L16:100
2022-12-12 12:19:44.083089 [ERR] switch_core_video.c:3044 This function is not available, libpng not installed
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '0' to 'mute'
2022-12-12 12:19:44.083089 [INFO] switch_ivr_async.c:219 Digit parser mod_conference: Setting realm to 'conf'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding 0/conf/0 callback: 0x7f2035415dd0 data: 0x7f2018231438
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '*' to 'deaf mute'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding */conf/0 callback: 0x7f2035415dd0 data: 0x7f2018231468
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '9' to 'energy up'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding 9/conf/0 callback: 0x7f2035415dd0 data: 0x7f2018231498
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '8' to 'energy equ'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding 8/conf/0 callback: 0x7f2035415dd0 data: 0x7f20182314c8
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '7' to 'energy dn'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding 7/conf/0 callback: 0x7f2035415dd0 data: 0x7f20182314f8
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '3' to 'vol talk up'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding 3/conf/0 callback: 0x7f2035415dd0 data: 0x7f2018231528
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '2' to 'vol talk zero'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding 2/conf/0 callback: 0x7f2035415dd0 data: 0x7f2018231558
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '1' to 'vol talk dn'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding 1/conf/0 callback: 0x7f2035415dd0 data: 0x7f2018231588
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '6' to 'vol listen up'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding 6/conf/0 callback: 0x7f2035415dd0 data: 0x7f20182315b8
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '5' to 'vol listen zero'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding 5/conf/0 callback: 0x7f2035415dd0 data: 0x7f20182315e8
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '4' to 'vol listen dn'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding 4/conf/0 callback: 0x7f2035415dd0 data: 0x7f2018231618
2022-12-12 12:19:44.083089 [DEBUG] conference_member.c:106 sofia/drachtio_mrf/nobody@172.25.0.166:5060 binding '#' to 'hangup'
2022-12-12 12:19:44.083089 [DEBUG] switch_ivr_async.c:344 Digit parser mod_conference: binding #/conf/0 callback: 0x7f2035415dd0 data: 0x7f2018231648
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.083089 [DEBUG] conference_loop.c:1338 Setup timer soft success interval: 20  samples: 160 from codec PCMU
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.183164 [DEBUG] switch_rtp.c:7759 Correct audio ip/port confirmed.
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:44.203086 [DEBUG] switch_rtp.c:1921 rtcp_stats_init: audio ssrc[1089714847] base_seq[20280]
2022-12-12 12:19:47.523163 [WARNING] switch_core_file.c:424 File has 2 channels, muxing to 1 channel will occur.
2de1572e-17e3-4b9b-8856-60a8b13e097d 2022-12-12 12:19:47.523163 [DEBUG] conference_member.c:1494 Queueing file https://vgmsite.com/soundtracks/fortnite-emotes-chapter-1-gamerip-2017/jhqrpbsrpm/01-02.%20Dance%20Moves%20%28Version%202%29.mp3 for play
2022-12-12 12:20:06.077246 [CONSOLE] switch_loadable_module.c:1803 Successfully Loaded [mod_logfile]
```

Backtrace
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f205b079537 in __GI_abort () at abort.c:79
#2  0x00007f205b0d2768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f205b1f03a5 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f205b0d9a5a in malloc_printerr (str=str@entry=0x7f205b1ee072 "free(): invalid size") at malloc.c:5347
#4  0x00007f205b0dac24 in _int_free (av=<optimized out>, p=0x7f2024187010, have_lock=0) at malloc.c:4177
#5  0x00007f205b630037 in switch_buffer_destroy (buffer=buffer@entry=0x7f20240879d8) at src/switch_buffer.c:398
#6  0x00007f2034ff13b0 in free_context (context=0x7f20240878b8) at mod_shout.c:249
#7  0x00007f2034ff1482 in free_context (context=<optimized out>) at mod_shout.c:922
#8  shout_file_close (handle=<optimized out>) at mod_shout.c:925
#9  0x00007f205b6518fd in switch_core_file_close (fh=fh@entry=0x7f2024049ed8) at src/switch_core_file.c:955
#10 0x00007f203537da69 in http_file_file_close (handle=<optimized out>) at mod_httapi.c:3059
#11 0x00007f205b6518fd in switch_core_file_close (fh=fh@entry=0x7f2024049b50) at src/switch_core_file.c:955
#12 0x00007f203543045f in conference_file_close (conference=0x7f2018227f48, node=0x7f2024049b50) at conference_file.c:111
#13 0x00007f203542b9cd in conference_member_add_file_data (member=member@entry=0x7f20588ec2f0, data=0x7f2018277ef8, file_data_len=320) at conference_member.c:544
#14 0x00007f2035416a35 in conference_loop_output (member=member@entry=0x7f20588ec2f0) at conference_loop.c:1542
#15 0x00007f2035404a48 in conference_function (session=0x7f2028035bf8, data=<optimized out>) at mod_conference.c:2487
#16 0x00007f205b663645 in switch_core_session_exec (session=session@entry=0x7f2028035bf8, application_interface=application_interface@entry=0x556ca8c2dc18,
    arg=0x7f202404cde0 "conf:bc3f20fd-7a57-49f7-90c6-caacbe4121ac:conference") at src/switch_core_session.c:2891
#17 0x00007f205b663d50 in switch_core_session_execute_application_get_flags (session=session@entry=0x7f2028035bf8, app=app@entry=0x7f202404cca0 "conference",
    arg=<optimized out>, arg@entry=0x7f202404cde0 "conf:bc3f20fd-7a57-49f7-90c6-caacbe4121ac:conference", flags=flags@entry=0x0) at src/switch_core_session.c:2756
#18 0x00007f205b70ee1a in switch_ivr_parse_event (session=0x7f2028035bf8, event=<optimized out>) at src/switch_ivr.c:646
#19 0x00007f205b70f9e5 in switch_ivr_parse_next_event (session=session@entry=0x7f2028035bf8) at src/switch_ivr.c:802
#20 0x00007f205b70faa8 in switch_ivr_parse_all_events (session=session@entry=0x7f2028035bf8) at src/switch_ivr.c:937
#21 0x00007f205b711198 in switch_ivr_park (session=session@entry=0x7f2028035bf8, args=args@entry=0x0) at src/switch_ivr.c:1148
#22 0x00007f20358c94b9 in socket_function (session=<optimized out>, data=<optimized out>) at mod_event_socket.c:542
#23 0x00007f205b663645 in switch_core_session_exec (session=session@entry=0x7f2028035bf8, application_interface=application_interface@entry=0x556ca8bfb920,
    arg=0x7f20280466e0 "${sip_h_X-esl-outbound} async full") at src/switch_core_session.c:2891
#24 0x00007f205b663d50 in switch_core_session_execute_application_get_flags (session=session@entry=0x7f2028035bf8, app=0x7f20280466d8 "socket", arg=<optimized out>,
    flags=flags@entry=0x0) at src/switch_core_session.c:2756
#25 0x00007f205b668192 in switch_core_standard_on_execute (session=0x7f2028035bf8) at src/switch_core_state_machine.c:354
#26 switch_core_session_run (session=0x7f2028035bf8) at src/switch_core_state_machine.c:651
#27 0x00007f205b6610b0 in switch_core_session_thread (thread=<optimized out>, obj=0x7f2028035bf8) at src/switch_core_session.c:1709
#28 0x00007f205b65ca97 in switch_core_session_thread_pool_worker (thread=0x7f202805aeb0, obj=<optimized out>) at src/switch_core_session.c:1772
#29 0x00007f205b233ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#30 0x00007f205b153a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by manticode** [comment]
My first thoughts are that this fault is related to https://github.com/signalwire/freeswitch/issues/1643

**Comment by two56** [comment]
I tested with mono files and can confirm it avoids the crash.

**Comment by dsatfire** [comment]
Seeing similar behavior with mono files.
