### ISSUE TITLE
FS crashes randomly 

### ISSUE THREAD

**Issue by xxmcf** [signalwire/freeswitch#1999]
FreeSWITCH crashes randomly with core dump.

Freeswitch Version 1.10.7
OS Distribution : CentOS Linux release 7.4.1708 (Core)

dump infos as follows:

(gdb) bt full
#0  0x00007f826b7835bd in malloc_consolidate () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f826b7844fe in _int_free () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f826f2c741d in apr_allocator_destroy (allocator=0x7f8150033070) at memory/unix/apr_pools.c:111
        index = <optimized out>
        node = <optimized out>
#3  0x00007f826f2c7d8e in apr_pool_destroy (pool=<optimized out>) at memory/unix/apr_pools.c:804
        active = <optimized out>
        allocator = <optimized out>
#4  0x00007f826ef9df07 in pool_thread (thread=<optimized out>, obj=<optimized out>) at src/switch_core_memory.c:603
        pop = 0x7f8150029398
        x = 4
        done = 0
        len = <optimized out>
#5  0x00007f826f2cce40 in dummy_worker (opaque=0x7f826f9f2c40) at threadproc/unix/thread.c:151
        thread = 0x7f826f9f2c40
#6  0x00007f826bad2e25 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#7  0x00007f826b80034d in clone () from /lib64/libc.so.6
No symbol table info available.

**Comment by andywolk** [comment]
This dump does not have enough information to figure out what was going on.
