### ISSUE TITLE
FreeSwitch Crashes Randomly 

### ISSUE THREAD

**Issue by adnanshoeb** [signalwire/freeswitch#2035]
**Environment:**

OS: Debian 11
Arch: AMD64
[backtrace-docker-debian10.log](https://github.com/signalwire/freeswitch/files/11222577/backtrace-docker-debian10.log)

Application version: 1.10.9

**Additional information:**

This GS is getting crashed randomly. 
SIP and WebRTC services are being consumed

Trace:
[backtrace-ec2-amd64.log](https://github.com/signalwire/freeswitch/files/11222568/backtrace-ec2-amd64.log)

**Comment by andywolk** [comment]
you need to install sofia-sip debugging symbols and redo the bt.

**Comment by BayuKrisnawan** [comment]
Hi @andywolk  

This is new backtrace log with sofia debugging symbols. 
It happened randomly when restarting sofia profile (tls/webrtc active) and there are active calls. 
Btw @Adnanshoeb is my team.

Additional Info :
- Debian-11 (AMD64)
- freeswitch 1.10.9

[backtrace-amd64-debian11.log](https://github.com/signalwire/freeswitch/files/11228448/backtrace-amd64-debian11.log)

**Comment by youzoulalala** [comment]
Freeswitch Crashes Randomly when using webrtc

**Comment by uyuy2043** [comment]
I have the same issue ,when i ues 50 call 50 webrtc extension，at the same time, WebRTC cannot connect :
#0  0x00007f0fdcb8dce1 in raise () from /lib/x86_64-linux-gnu/libc.so.6 
#1  0x00007f0fdcb77537 in abort () from /lib/x86_64-linux-gnu/libc.so.6 
#2  0x00007f0fdcb7740f in ?? () from /lib/x86_64-linux-gnu/libc.so.6 
#3  0x00007f0fdcb86662 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6 
#4  0x00007f0fdc64ff58 in nua_destroy () from /lib/libsofia-sip-ua.so.0 
#5  0x00007f0fabc1beb4 in sofia_profile_thread_run (thread=<optimized out>, obj=0x7f0f602283c0) at sofia.c:3569 
#6  0x00007f0fdcd31ea7 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0 
#7  0x00007f0fdcc51a2f in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by BayuKrisnawan** [comment]
Yeah,
No update yet hehehe. 
I'm able to use nginx infront of freeswitch.
Nginx  --> WS --> FreeSwitch  or put kamailio/opensips in front of it.

**Comment by themsley-voiceflex** [comment]
This can probably be closed, duplicate of #2283
