### ISSUE TITLE
t.38 rxfax causes regular crashes

### ISSUE THREAD

**Issue by garnathan** [signalwire/freeswitch#2071]
**Describe the bug**
FreeSwitch crashes regularly when using t.38 ```rxfax``` for an unknown reason on latest 1.10.7. Looking into the backtrace, it appears that ```msg``` variable becomes corrupt or null during a fax receive. Previous version before upgrade was 1.6.20 which was stable for this call flow, crashes only occur since upgrading to 1.10.7.

Backtrace snippet (full trace attached):
```
#0  bit_reverse (to=to@entry=0x7f3f58c072b0 "h\372\210]\365\337\\'\220\207\066n\306}\350C*\350\002\036\334\374\310\340\342q\273k\037\r\017\343\036\334Hs{\030\367\017\206\034-\005/M\027N\267\337&\352\353\246\377\377.\241\276\204?\177", from=0x7f3f541c2a7e "\026_\021\272\257\373:\344;\372\372\037]\351c\267\235Pq\021\027/\301\377\344\035ޱ\020\177\\\217\241\207\377WL\217\374\376\251S\357\376\377\213\354\303\347]\227}\206K;\320", <incomplete sequence \340>, len=len@entry=54) at bit_operations.c:111
#1  0x00007f3f84bfc815 in process_rx_data (t=<optimized out>, user_data=0x7f3f5406b618, data_type=8, field_type=<optimized out>, buf=<optimized out>, len=54) at t38_terminal.c:572
#2  0x00007f3f84bf5a6f in t38_core_rx_ifp_stream (s=s@entry=0x7f3f5407ff30, buf=<optimized out>, len=len@entry=59, log_seq_no=log_seq_no@entry=2804) at t38_core.c:661#3  0x00007f3f84bf5d1d in t38_core_rx_ifp_packet (s=0x7f3f5407ff30, buf=<optimized out>, len=59, seq_no=2804) at t38_core.c:760#4  0x00007f3f5aeece93 in udptl_rx_packet (s=0x7f3f541e9378, buf=0x7f3f541c2a38 "\n\365;\320", <incomplete sequence \340>, len=244) at udptl.c:260
#5  0x00007f3f5aef3830 in mod_spandsp_fax_process_fax (session=0x7f3f6425c9c8, data=0x7f3f5409f050 "/apollo/_env/VineCanaryPBX-public.1271325995.1420586722.1143248460/var/output/receivedFaxFiles/FAX-e7c5ee3f-4a7f-4e51-80f5-1d7d73641e4e.tif", app_mode=FUNCTION_RX) at mod_spandsp_fax.c:1752
```

**To Reproduce**
1. Using this example inbound configuration...

```
    <extension name="fax_receive" continue="false">
      <condition field="destination_number" expression="\+12345678900">
        <action application="answer" />
        <action application="playback" data="silence_stream://2000"/>
        <action application="set" data="fax_enable_t38_request=true"/>
        <action application="set" data="fax_enable_t38=true"/>
        <action application="rxfax" data="/apollo/_env/VineCanaryPBX-public.1271325995.1420586722.1143248460/var/output/receivedFaxFiles/FAX-${uuid}.tif"/>
        <action application="hangup"/>
      </condition>
    </extension>
```

2. Send a fax using:
```
'fs_cli -x "originate {origination_caller_id_number=+12345678923,'
               'ignore_early_media=true,absolute_codec_string=\'PCMU\','
               'fax_enable_t38=true,fax_verbose=true,fax_use_ecm=false,fax_enable_t38_request=false}'
               'sofia/external/' + destination_uri + ' &txfax(' + fax_file + ')"'
```

4. If run every minute, crashes occur every approx 30 minutes, but can take as long as 180 minutes at times, so not on every call, but occurs on the exact same call flow. 
5. Fax file gets written to disk but with no content.
6. FreeSWITCH crashes

**Expected behavior**
Call to complete successfully, fax file to be written, FreeSwitch to not crash

**Package version or git hash**
 - FreeSwitch Version 1.10.7
 - Spandsp Version 3.0.0

**Trace logs**
Crash/restart occurs at ```2023-05-02 07:18:44``` while processing call ```b8733ca5-44df-4681-907f-5247d384452a```

[freeswitch.txt](https://github.com/signalwire/freeswitch/files/11372834/freeswitch.txt)

**backtrace from core file**

[backtrace_1.log](https://github.com/signalwire/freeswitch/files/11372640/backtrace_1.log)

**Comment by andywolk** [comment]
What else has changed? x86 -> x64? what was your previous setup? 32 bit?

**Comment by garnathan** [comment]
Running on the exact same hardware and OS as before with 1.6.20. 

x86_64, Amazon Linux 2 (which is RHEL based) on AWS EC2 instances, m5.xl instance types. Nothing has changed in terms of hardware or OS.

**Comment by upcFrost** [comment]
Hi, we seem to be having similar issue. I'm not entirely sure if it's t38 or not, but as soon as I've enabled inbound faxes the FS instance which was up and running for 3 months crashed the same day. Don't really know how to reproduce it though
