### ISSUE TITLE
memory leak observed in mod_conference (v1.10.10)

### ISSUE THREAD

**Issue by jvm7293** [signalwire/freeswitch#2302]
**Describe the bug**
Memory keeps growing when a conference is created on FS 1.10.10.

**To Reproduce**
1. create a conference with one publisher and one subscriber
2. observe the memory growing as the call remains active.

**Expected behavior**
Memory should not be constantly growing when a conference conference. 
The memory usage should be similar to that observed in FS 1.10.7

**Comment by andywolk** [comment]
Are you able to run under valgrind or address sanitizer?

**Comment by andywolk** [comment]
make sure you have these options set first
```
export ASAN_OPTIONS=log_path=stdout:disable_coredump=0:unmap_shadow_on_exit=1:fast_unwind_on_malloc=0
```

**Comment by jvm7293** [comment]
The leak disappears by removing the changes in conference_loop.c (conference_loop_launch_input function) and mod_conference.c related to changes for conference_loop_launch_input.  Removing those changes from 1.10.10 removes the leak.  I reverted back the handling of the conference input loop to the implementation from 1.10.7 and the leak goes away.

**Comment by jvm7293** [comment]
> make sure you have these options set first
> 
> ```
> export ASAN_OPTIONS=log_path=stdout:disable_coredump=0:unmap_shadow_on_exit=1:fast_unwind_on_malloc=0
> ```

Thanks. This is to prevent FS from aborting when using asan, right?

**Comment by andywolk** [comment]
Check what's in `cat /proc/sys/kernel/core_pattern`
and configure properly to have a code dump:
```
ulimit -c unlimited
echo '/cores/core.%s.%E.%e.%p.%t' > /proc/sys/kernel/core_pattern
```

**Comment by jvm7293** [comment]
To compile FS with address sanitizer, just configure FS with --enable-address-sanitizer.

**Comment by jvm7293** [comment]
@andywolk - I configured FS with asan and I set the ASAN_OPTIONS as you specified.  When FS starts it immediately aborts.  Do i need to perform an additional step in order to allow FS to start.  FS is running in debian container.

The output of /proc/sys/kernel/core_pattern is: 
`|/var/mnt/core-dump-handler/cdc -c=%c -e=%e -p=%p -s=%s -t=%t -d=/var/mnt/core-dump-handler/cores -h=%h -E=%E`

1. configured FS with--enable-address-sanitizer
2. export ASAN_OPTIONS=log_path=stdout:disable_coredump=0:unmap_shadow_on_exit=1:fast_unwind_on_malloc=0
3. When FS starts it aborts with the following output
```
SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:861 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long)
Shadow bytes around the buggy address:
  0x0c0c80000660: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c0c80000670: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
  0x0c0c80000680: fd fd fd fd fd fd fd fd fa fa fa fa 00 00 00 00
  0x0c0c80000690: 00 00 00 00 fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c0c800006a0: fa fa fa fa 00 00 00 00 00 00 00 00 fa fa fa fa
=>0x0c0c800006b0: 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa
  0x0c0c800006c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c800006d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c800006e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c800006f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c80000700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==504==ABORTING
```

**Comment by andywolk** [comment]
`/proc/sys/kernel/core_pattern` does not look like I showed

**Comment by jvm7293** [comment]
I tried overwriting that files as you specified, but I was not able to do because the file is read only.   I got the following error:
```
root@sip-dev-0-switch-566c7fd65-9v2qd:/# echo '/cores/core.%s.%E.%e.%p.%t' > /proc/sys/kernel/core_pattern
bash: /proc/sys/kernel/core_pattern: Read-only file system
```
I tried changing permissions on the file, but I did not succeed with that.

**Comment by jvm7293** [comment]
I might have to run the container using the privileged access option.  I'll get back to you after I can successfully update that file.

**Comment by jvm7293** [comment]
@andywolk 
I modified core_pattern like you showed.
From my FS docker container:
- root@sip-dev-0-switch-65bbdcf6d8-lf27p:/# ulimit   
unlimited
- root@sip-dev-0-switch-65bbdcf6d8-lf27p:/# env | grep ASAN
ASAN_OPTIONS=log_path=stdout:disable_coredump=0:unmap_shadow_on_exit=1:fast_unwind_on_malloc=0
root@sip-dev-0-switch-65bbdcf6d8-lf27p:/# cat /proc/sys/kernel/core_pattern
/cores/core.%s.%E.%e.%p.%t

When FS starts it aborts with the following output
#
2023-11-14 18:35:54.806309 0.00% [NOTICE] switch_loadable_module.c:389 Adding AP=================================================================
==4124==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6060000435c0 at pc 0x7fed076281d0 bp 0x7fed01711250 sp 0x7fed01710a00
READ of size 16 at 0x6060000435c0 thread T15
    #0 0x7fed076281cf in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long) ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:861
    #1 0x7fed07628908 in __interceptor_memcmp ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:892
    #2 0x7fed07628908 in __interceptor_memcmp ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:887
    #3 0x7fed05b64719 in tport_getaddrinfo (/usr/local/lib/libsofia-sip-ua.so.0+0x14c719)
    #4 0x7fed05b63e43 in tport_server_addrinfo (/usr/local/lib/libsofia-sip-ua.so.0+0x14be43)
    #5 0x7fed05b63613 in tport_bind_server (/usr/local/lib/libsofia-sip-ua.so.0+0x14b613)
    #6 0x7fed05b62d42 in tport_tbind (/usr/local/lib/libsofia-sip-ua.so.0+0x14ad42)
    #7 0x7fed05ab2c5c in nta_agent_add_tport (/usr/local/lib/libsofia-sip-ua.so.0+0x9ac5c)
    #8 0x7fed05af8279 in nua_stack_init_transport (/usr/local/lib/libsofia-sip-ua.so.0+0xe0279)
    #9 0x7fed05ae01c1 in nua_stack_init (/usr/local/lib/libsofia-sip-ua.so.0+0xc81c1)
    #10 0x7fed05b509ae in su_pthread_port_clone_main (/usr/local/lib/libsofia-sip-ua.so.0+0x1389ae)
    #11 0x7fed060f2043  (/lib/x86_64-linux-gnu/libc.so.6+0x89043)
    #12 0x7fed0617261b  (/lib/x86_64-linux-gnu/libc.so.6+0x10961b)

0x6060000435c0 is located 0 bytes to the right of 64-byte region [0x606000043580,0x6060000435c0)
allocated by thread T15 here:
    #0 0x7fed076369cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7fed06159095 in getaddrinfo (/lib/x86_64-linux-gnu/libc.so.6+0xf0095)
    #2 0x7fed076210b3 in __interceptor_getaddrinfo ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:2667
    #3 0x7fed05b460aa in su_getaddrinfo (/usr/local/lib/libsofia-sip-ua.so.0+0x12e0aa)
    #4 0x7fed05b64410 in tport_getaddrinfo (/usr/local/lib/libsofia-sip-ua.so.0+0x14c410)
    #5 0x7fed05b63e43 in tport_server_addrinfo (/usr/local/lib/libsofia-sip-ua.so.0+0x14be43)
    #6 0x7fed05b63613 in tport_bind_server (/usr/local/lib/libsofia-sip-ua.so.0+0x14b613)
    #7 0x7fed05b62d42 in tport_tbind (/usr/local/lib/libsofia-sip-ua.so.0+0x14ad42)
    #8 0x7fed05ab2c5c in nta_agent_add_tport (/usr/local/lib/libsofia-sip-ua.so.0+0x9ac5c)
    #9 0x7fed05af8279 in nua_stack_init_transport (/usr/local/lib/libsofia-sip-ua.so.0+0xe0279)
    #10 0x7fed05ae01c1 in nua_stack_init (/usr/local/lib/libsofia-sip-ua.so.0+0xc81c1)
    #11 0x7fed05b509ae in su_pthread_port_clone_main (/usr/local/lib/libsofia-sip-ua.so.0+0x1389ae)
    #12 0x7fed060f2043  (/lib/x86_64-linux-gnu/libc.so.6+0x89043)
    #13 0x7fed0617261b  (/lib/x86_64-linux-gnu/libc.so.6+0x10961b)

Thread T15 created by T12 here:
    #0 0x7fed075c7726 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:207
    #1 0x7fed05b50712 in su_pthreaded_port_start (/usr/local/lib/libsofia-sip-ua.so.0+0x138712)
    #2 0x7fed05b53c91 in su_epoll_clone_start (/usr/local/lib/libsofia-sip-ua.so.0+0x13bc91)
    #3 0x7fed05b4eec2 in su_default_clone_start (/usr/local/lib/libsofia-sip-ua.so.0+0x136ec2)
    #4 0x7fed05b4f14a in su_clone_start (/usr/local/lib/libsofia-sip-ua.so.0+0x13714a)
    #5 0x7fed05ad7bc3 in nua_create (/usr/local/lib/libsofia-sip-ua.so.0+0xbfbc3)
    #6 0x7fed019fee86 in sofia_profile_thread_run /root/freeswitch-h2o/src/mod/endpoints/mod_sofia/sofia.c:3227
    #7 0x7fed0724066d in dummy_worker (/usr/local/freeswitch/lib/libfreeswitch.so.1+0xabe66d)
    #8 0x7fed060f2043  (/lib/x86_64-linux-gnu/libc.so.6+0x89043)

Thread T12 created by T0 here:
    #0 0x7fed075c7726 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:207
    #1 0x7fed07240b1d in fspr_thread_create (/usr/local/freeswitch/lib/libfreeswitch.so.1+0xabeb1d)
    #2 0x7fed068b82b9 in switch_thread_create src/switch_apr.c:702
    #3 0x7fed01a03764 in launch_sofia_profile_thread /root/freeswitch-h2o/src/mod/endpoints/mod_sofia/sofia.c:3629
    #4 0x7fed01a1f898 in config_sofia /root/freeswitch-h2o/src/mod/endpoints/mod_sofia/sofia.c:6345
    #5 0x7fed019ddb5f in mod_sofia_load /root/freeswitch-h2o/src/mod/endpoints/mod_sofia/mod_sofia.c:6673
    #6 0x7fed06a980e0 in switch_loadable_module_load_file src/switch_loadable_module.c:1720
    #7 0x7fed06a98c32 in switch_loadable_module_load_module_ex src/switch_loadable_module.c:1827
    #8 0x7fed06a9ae5c in switch_loadable_module_init src/switch_loadable_module.c:2245
    #9 0x7fed06989324 in switch_core_init_and_modload src/switch_core.c:2470
    #10 0x55d1b311b4ff in main src/switch.c:1201
    #11 0x7fed060901c9  (/lib/x86_64-linux-gnu/libc.so.6+0x271c9)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:861 in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long)
Shadow bytes around the buggy address:
  0x0c0c80000660: fd fd fd fd fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c0c80000670: fa fa fa fa fd fd fd fd fd fd fd fd fa fa fa fa
  0x0c0c80000680: fd fd fd fd fd fd fd fd fa fa fa fa 00 00 00 00
  0x0c0c80000690: 00 00 00 00 fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c0c800006a0: fa fa fa fa 00 00 00 00 00 00 00 00 fa fa fa fa
=>0x0c0c800006b0: 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa
  0x0c0c800006c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c800006d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c800006e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c800006f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c80000700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==4124==ABORTING
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer:DEADLYSIGNAL
ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)

**Comment by jvm7293** [comment]
@andywolk any idea as to why freeswitch is aborting for me on startup with address sanitizer enabled?  Could it have something to do with the way I'm starting up freeswitch?
I'm starting up freeswitch this way:
`/usr/local/freeswitch/bin/freeswitch -conf /etc/freeswitch -log /usr/local/freeswitch/ -db /dev/shm -nonat &`
