### ISSUE TITLE
Segfault at switch_hash_equalkeys 

### ISSUE THREAD

**Issue by greenbea** [signalwire/freeswitch#2421]
**Describe the bug**
Freeswitch crashes randomly

**Package version or git hash**
 - Version 1.10.11

**backtrace from core file**
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:287
287     ../sysdeps/x86_64/multiarch/strcmp-avx2.S: No such file or directory.
[Current thread is 1 (Thread 0x7f2995d7c6c0 (LWP 2339913))]


#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:287
#1  0x00007f2a7a480db9 in switch_hash_equalkeys (k1=<optimized out>, k2=<optimized out>) at ./src/include/switch_hashtable.h:216
#2  0x00007f2a7a57f739 in switch_hashtable_search (h=0x7f2a680569b0, k=k@entry=0x7f2874014990) at src/switch_hashtable.c:236
#3  0x00007f2a7a481315 in switch_core_hash_find (hash=<optimized out>, key=key@entry=0x7f2874014990 "America/New_York") at src/switch_core_hash.c:268
#4  0x00007f2a7a574012 in switch_lookup_timezone (tz_name=tz_name@entry=0x7f2874014990 "America/New_York") at src/switch_time.c:1387
#5  0x00007f2a7a5744c9 in switch_time_exp_tz_name (tz=tz@entry=0x7f2874014990 "America/New_York", tm=tm@entry=0x7f2995d7b3e0, thetime=1712325735795600) at src/switch_time.c:1459
#6  0x00007f2a7a56f096 in switch_xml_std_datetime_check (xcond=xcond@entry=0x7f2874016fb0, offset=0x0, tzname=tzname@entry=0x7f2874014990 "America/New_York") at src/switch_xml.c:3177
#7  0x00007f2a72448989 in parse_exten (session=session@entry=0x7f2a44512528, caller_profile=caller_profile@entry=0x7f287430c998, xexten=xexten@entry=0x7f2874016ed0,
    extension=extension@entry=0x7f2995d7b9a0, exten_name=exten_name@entry=0x7f2874321b99 "Company Info", recur=recur@entry=0) at mod_dialplan_xml.c:179
#8  0x00007f2a7244a9f5 in dialplan_hunt (session=0x7f2a44512528, arg=<optimized out>, caller_profile=0x7f287430c998) at mod_dialplan_xml.c:701
#9  0x00007f2a7a496408 in switch_core_standard_on_routing (session=0x7f2a44512528) at src/switch_core_state_machine.c:276
#10 switch_core_session_run (session=<optimized out>) at src/switch_core_state_machine.c:640
#11 0x00007f2a7a48f5c0 in switch_core_session_thread (thread=<optimized out>, obj=0x7f2a44512528) at src/switch_core_session.c:1727
#12 0x00007f2a7a48ad57 in switch_core_session_thread_pool_worker (thread=0x7f29fc20e210, obj=<optimized out>) at src/switch_core_session.c:1791
#13 0x00007f2a7a2a8134 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#14 0x00007f2a7a3287dc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

I had this same segfault more than once.

**Comment by andywolk** [comment]
This should be fixed by
- https://github.com/signalwire/freeswitch/pull/2371

Closing as a duplicate.
