### ISSUE TITLE
crash in SSL on websocket connection 

### ISSUE THREAD

**Issue by rahuravi** [signalwire/freeswitch#2469]
crash in SSL on websocket connection 

**backtrace from core file**

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./freeswitch -nc'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f58f60957dd in _int_malloc (av=av@entry=0x7f5484000020, bytes=bytes@entry=40) at malloc.c:3615
3615	malloc.c: No such file or directory.
[Current thread is 1 (Thread 0x7f4f397f2700 (LWP 63175))]
(gdb) 
(gdb) bt
#0  0x00007f58f60957dd in _int_malloc (av=av@entry=0x7f5484000020, bytes=bytes@entry=40) at malloc.c:3615
#1  0x00007f58f609772a in __GI___libc_malloc (bytes=40) at malloc.c:3068
#2  0x00007f58f6ab08d9 in CRYPTO_zalloc () at /lib/x86_64-linux-gnu/libcrypto.so.1.1
#3  0x00007f58f6c2f2bf in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#4  0x00007f58f6c3203b in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#5  0x00007f58f6c32a56 in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#6  0x00007f58f6c45392 in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#7  0x00007f58f6c454c3 in SSL_write () at /lib/x86_64-linux-gnu/libssl.so.1.1
#8  0x00007f58b2655cf4 in ws_raw_write (wsh=wsh@entry=0x7f5897a1d4c0, data=data@entry=0x7f54844859d0, bytes=bytes@entry=169) at ws.c:674
#9  0x00007f58b2656e62 in ws_write_frame (wsh=0x7f5897a1d4c0, oc=<optimized out>, data=0x7f5484452290, bytes=165) at ws.c:1322
```

**Comment by themsley-voiceflex** [comment]
What versions of freeswitch & sofia-sip are you using?

**Comment by suiyuemanbu** [comment]
is your  wss.pem  ok?
