### ISSUE TITLE
conference recording crash

### ISSUE THREAD

**Issue by tangshiixang** [signalwire/freeswitch#52]
version: freeswitch 1.8
call statck:
```
(gdb) bt
#0 0x00007f2680a6f067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1 0x00007f2680a70448 in __GI_abort () at abort.c:89
#2 0x00007f2680aad1b4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7f2680ba2210 "*** Error in `%s': %s: 0x%s ***\n")
at ../sysdeps/posix/libc_fatal.c:175
#3 0x00007f2680ab298e in malloc_printerr (action=1, str=0x7f2680b9e42a "realloc(): invalid next size", ptr=) at malloc.c:4996
#4 0x00007f2680ab576b in _int_realloc (av=av@entry=0x7f2320000020, oldp=oldp@entry=0x7f2320036170, oldsize=oldsize@entry=1552, nb=nb@entry=544) at malloc.c:4234
#5 0x00007f2680ab6769 in __GI___libc_realloc (oldmem=0x7f2320036180, bytes=523) at malloc.c:3029
#6 0x00007f260856d044 in av_buffer_realloc () from /usr/lib/x86_64-linux-gnu/libavutil.so.54
#7 0x00007f2608dd9236 in avcodec_encode_audio2 () from /usr/lib/x86_64-linux-gnu/libavcodec.so.56
#8 0x00007f2609c790dc in av_file_write (handle=0x2096, data=0x67a6, len=0x6) at avformat.c:2036
#9 0x00007f2681f23caf in switch_core_file_write (fh=0x7f25c02706a0, data=0x7f2320004ce0, len=0x7f25c4675708) at src/switch_core_file.c:670
#10 0x00007f26415c068c in conference_record_thread_run (thread=0x2096, obj=0x766b00) at conference_record.c:377
#11 0x00007f268222d110 in dummy_worker (opaque=0x7f25c02709f0) at threadproc/unix/thread.c:151
#12 0x00007f268144b064 in start_thread (arg=0x7f25c4676700) at pthread_create.c:309
#13 0x00007f2680b2262d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

(gdb) f 9
#9 0x00007f2681f23caf in switch_core_file_write (fh=0x7f25c02706a0, data=0x7f2320004ce0, len=0x7f25c4675708) at src/switch_core_file.c:670
670 if ((status = fh->file_interface->file_write(fh, data, len)) == SWITCH_STATUS_SUCCESS) {

(gdb) p len
$1 = (switch_size_t *) 0x7f25c4675708

(gdb) p *len
$2 = 960

(gdb) p *fh
$3 = {file_interface = 0x2fb6300, flags = 526346, fd = 0x0, samples = 0, samplerate = 48000, native_rate = 48000, channels = 2, real_channels = 2, format = 0,
sections = 0, seekable = 0, sample_count = 0, speed = 0, memory_pool = 0x7f25c0270598, prebuf = 0, interval = 0, private_info = 0x7f232000b6d0, handler = 0x0,
pos = 0, audio_buffer = 0x0, sp_audio_buffer = 0x0, thresh = 0, silence_hits = 0, offset_pos = 0, samples_in = 0, samples_out = 45617280, vol = 0, resampler = 0x0,
buffer = 0x0, dbuf = 0x0, dbuflen = 0, pre_buffer = 0x0, pre_buffer_data = 0x0, pre_buffer_datalen = 0, file = 0x7f26415c85d0 "conference_record.c",
func = 0x7f26415c8720 <func.20072> "conference_record_thread_run", line = 276, file_path = 0x7f232000b6a8 "2_1570779353373.mp4",
spool_path = 0x0, prefix = 0x0, max_samples = 0, params = 0x7f2320005cb0, cur_channels = 0, cur_samplerate = 0, stream_name = 0x0, modname = 0x0, mm = {
samplerate = 48000, channels = 2, keyint = 60, ab = 128, vb = 2177, vw = 1920, vh = 1080, cbr = 0, fps = 15, source_fps = 0, vbuf = 0,
vprofile = SWITCH_VIDEO_PROFILE_BASELINE, vencspd = SWITCH_VIDEO_ENCODE_SPEED_DEFAULT, try_hardware_encoder = 1 '\001', scale_w = 0, scale_h = 0,
fmt = VPX_IMG_FMT_NONE, auth_username = 0x0, auth_password = 0x0}, flag_mutex = 0x7f232000b5e0, duration = 0, vpos = 0, muxbuf = 0x0, muxlen = 0}

(gdb) p *(fh->file_interface)
$4 = {interface_name = 0x7f2609c812d0 "mod_av", file_open = 0x7f2609c79f90 <av_file_open>, file_close = 0x7f2609c79580 <av_file_close>,
file_truncate = 0x7f2609c76050 <av_file_truncate>, file_read = 0x7f2609c77c90 <av_file_read>, file_write = 0x7f2609c78da0 <av_file_write>,
file_read_video = 0x7f2609c775c0 <av_file_read_video>, file_write_video = 0x7f2609c77e70 <av_file_write_video>, file_seek = 0x7f2609c76360 <av_file_seek>,
file_set_string = 0x7f2609c762a0 <av_file_set_string>, file_get_string = 0x7f2609c761d0 <av_file_get_string>, file_pre_close = 0x0,
file_command = 0x7f2609c76060 <av_file_command>, extens = 0x7f2609e84900 <supported_formats>, rwlock = 0x2fb6398, refs = 19, reflock = 0x2fb63f8,
parent = 0x2fb6100, next = 0x0}
```
If you need more details, please let me know. Thank you!

**Comment by briankwest** [comment]
Please retest on 1.10.2

**Comment by crienzo** [comment]
Reopen if this is still a problem.
