### ISSUE TITLE
when fs_cli was terminaled(etc:kill pid),freeswitch crashed

### ISSUE THREAD

**Issue by harold-yh** [signalwire/freeswitch#559]
when telnet to freeswitch event socket,kill the telnet programe,freeswitch alse crashed too,maybe mod_event_socket.c has some problem。

Thread 755 "freeswitch" received signal SIGPIPE, Broken pipe
#0  __libc_write (nbytes=67, buf=0x7ffff47f77c8, fd=222) at ../sysdeps/unix/sysv/linux/write.c:26
#1  __libc_write (fd=222, buf=0x7ffff47f77c8, nbytes=67) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x00007ffff7ac49bd in apr_socket_send (sock=0x7fff6803c5e8, buf=0x7ffff47f77c8 "Disconnected, goodbye.\nSee you at ClueCon! http://www.cluecon.com/\n", len=0x7ffff5377318)
    at network_io/unix/sendrecv.c:43
#3  0x00007ffff7707d8f in switch_socket_send (sock=0x7fff6803c5e8, buf=0x7ffff47f77c8 "Disconnected, goodbye.\nSee you at ClueCon! http://www.cluecon.com/\n", len=0x7ffff5377368)
    at src/switch_apr.c:761
#4  0x00007ffff47ec644 in send_disconnect (listener=0x7fff6803c7d8, message=0x7ffff47f77c8 "Disconnected, goodbye.\nSee you at ClueCon! http://www.cluecon.com/\n") at mod_event_socket.c:647
#5  0x00007ffff47f431f in listener_run (thread=0x7fff5f568868, obj=0x7fff6803c7d8) at mod_event_socket.c:2805
#6  0x00007ffff7ac82de in dummy_worker (opaque=0x7fff5f568868) at threadproc/unix/thread.c:151
#7  0x00007ffff763dfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#8  0x00007ffff71f34cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by andywolk** [comment]
We can not reproduce. Please try this compiling manually and see if that helps:
```
--- a/src/mod/event_handlers/mod_event_socket/mod_event_socket.c
+++ b/src/mod/event_handlers/mod_event_socket/mod_event_socket.c
@@ -623,6 +623,7 @@ static void send_disconnect(listener_t *listener, const char *message)
 
 	char disco_buf[512] = "";
 	switch_size_t len, mlen;
+	switch_status_t send_result;
 
 	if (zstr(message)) {
 		message = "Disconnected.\n";
@@ -641,8 +642,8 @@ static void send_disconnect(listener_t *listener, const char *message)
 	if (!listener->sock) return;
 
 	len = strlen(disco_buf);
-	switch_socket_send(listener->sock, disco_buf, &len);
-	if (len > 0) {
+	send_result = switch_socket_send(listener->sock, disco_buf, &len);
+	if (send_result == SWITCH_STATUS_SUCCESS && len > 0) {
 		len = mlen;
 		switch_socket_send(listener->sock, message, &len);
 	}
```

**Comment by harold-yh** [comment]
I has do that,but it was crashed again.
when telnet localhost 8021,close the command window or kill the telnet process,it was crashed.

![image](https://user-images.githubusercontent.com/28439656/79525131-b8abbf80-8094-11ea-8fcb-c41bb99ac13f.png)
