### ISSUE TITLE
The main-thread reports memory allocation and release errors. 

### ISSUE THREAD

**Issue by baikaishui-ks** [signalwire/freeswitch#657]
The main-thread reports memory allocation and release errors. 
Usecase: 64 cpus, 16 GB memory, 3000 - 4000 calls

The following is the error time stack.

# when alloc
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/callcenter/bin/ccserver -nonat -nosql -nc -log /dev/shm -conf /usr/l'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000015548866f120 in _int_malloc (av=av@entry=0x154e60000020, bytes=bytes@entry=48) at malloc.c:4033
4033	malloc.c: No such file or directory.
[**Current thread is 1** (Thread 0x154bbf3fc700 (LWP 7398))]
(gdb) bt
#0  0x000015548866f120 in _int_malloc (av=av@entry=0x154e60000020, bytes=bytes@entry=48) at malloc.c:4033
#1  0x000015548867056a in __GI___libc_malloc (bytes=48) at malloc.c:3057
#2  0x0000155488cb81da in new_header (header_name=0x154e6062e1a0 "rtp_audio_in_flaw_total") at src/switch_event.c:934
#3  0x0000155488cb8859 in switch_event_base_add_header (event=0x154e6030c150, stack=SWITCH_STACK_BOTTOM, header_name=0x154e6062e1a0 "rtp_audio_in_flaw_total", data=0x154e6002daa0 "0") at src/switch_event.c:1085
#4  0x0000155488cb8f3c in switch_event_add_header_string (event=0x154e6030c150, stack=SWITCH_STACK_BOTTOM, header_name=0x154e6062e1a0 "rtp_audio_in_flaw_total", data=0x154e6002b470 "0") at src/switch_event.c:1221
#5  0x0000155488cb9539 in switch_event_dup (event=0x154bbf3fba58, todup=0x155284149130) at src/switch_event.c:1354
#6  0x0000155488c0b29f in switch_channel_get_variables (channel=0x155284191d90, event=0x154bbf3fba58) at src/switch_channel.c:4403
#7  0x0000155488c43dab in api_hook (session=0x155284288618, 
    hook_var=0x154e607aa8e8 "lua status.lua callout 07566351375 018897048953 +867566351375 018897048953 hangup 08043338-2300-48db-a70a-c25dd56be303 fc937963-93d1-4eaf-b76e-25dd8bf218a6 183.237.66.230:5060", use_session=1)
    at src/switch_core_state_machine.c:775
#8  0x0000155488c446a8 in switch_core_session_hangup_state (session=0x155284288618, force=SWITCH_TRUE) at src/switch_core_state_machine.c:860
#9  0x0000155488c40b23 in switch_core_session_run (session=0x155284288618) at src/switch_core_state_machine.c:616
#10 0x0000155488c39ddc in switch_core_session_thread (thread=0x154e445e5d30, obj=0x155284288618) at src/switch_core_session.c:1709
#11 0x0000155488c3a1cb in switch_core_session_thread_pool_worker (thread=0x154e445e5d30, obj=0x154e445e5bc0) at src/switch_core_session.c:1772
#12 0x0000155488fbb8ae in dummy_worker (opaque=0x154e445e5d30) at threadproc/unix/thread.c:151
#13 0x0000155488b2ffa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#14 0x00001554886e54cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```
#when release
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/callcenter/bin/ccserver -nonat -nosql -nc -log /dev/shm -conf /usr/l'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[**Current thread is 1** (Thread 0x14620e4bc700 (LWP 34516))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000146a6250c535 in __GI_abort () at abort.c:79
#2  0x0000146a62563508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x146a6266e28d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x0000146a62569c1a in malloc_printerr (str=str@entry=0x146a6266c43b "free(): invalid pointer") at malloc.c:5341
#4  0x0000146a6256b42c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4165
#5  0x0000146a62bb7265 in switch_event_destroy (event=0x14620e4b3400) at src/switch_event.c:1284
#6  0x0000146a62b07094 in switch_channel_execute_on (channel=0x1464f0191700, variable_prefix=0x146a62ef23e5 "execute_on_post_originate") at src/switch_channel.c:3762
#7  0x0000146a62bfb25c in switch_ivr_originate (session=0x1461b0013ac8, bleg=0x14620e4bab08, cause=0x14620e4bab04, 
    bridgeto=0x1464f06b2078 "{origination_uuid=419e285b-1d45-4309-977e-bc6655120c51,origination_caller_id_number=+867566351362,callout execute_on_ring='lua status.lua callout 07566351362 013560820253 +867566351362 013560820253 ri"..., 
    timelimit_sec=60, table=0x0, cid_name_override=0x0, cid_num_override=0x1464f0010250 "+867566351362", caller_profile_override=0x0, ovars=0x0, flags=0, cancel_cause=0x0, dh=0x0) at src/switch_ivr_originate.c:4177
#8  0x0000146a5aec38a3 in audio_bridge_function (session=0x1461b0013ac8, 
    data=0x1464f06b2078 "{origination_uuid=419e285b-1d45-4309-977e-bc6655120c51,origination_caller_id_number=+867566351362,callout execute_on_ring='lua status.lua callout 07566351362 013560820253 +867566351362 013560820253 ri"...)
    at mod_dptools.c:3625
#9  0x0000146a62b3c194 in switch_core_session_exec (session=0x1461b0013ac8, application_interface=0x55ed0c6647d0, 
    arg=0x1464f06b2078 "{origination_uuid=419e285b-1d45-4309-977e-bc6655120c51,origination_caller_id_number=+867566351362,callout execute_on_ring='lua status.lua callout 07566351362 013560820253 +867566351362 013560820253 ri"...)
    at src/switch_core_session.c:2891
#10 0x0000146a62b3b835 in switch_core_session_execute_application_get_flags (session=0x1461b0013ac8, app=0x1464f01a7308 "bridge", 
    arg=0x1464f06b2078 "{origination_uuid=419e285b-1d45-4309-977e-bc6655120c51,origination_caller_id_number=+867566351362,callout execute_on_ring='lua status.lua callout 07566351362 013560820253 +867566351362 013560820253 ri"..., flags=0x0)
    at src/switch_core_session.c:2756
#11 0x0000146a62c6dc29 in CoreSession::execute (this=0x1464f031b770, app=0x1464f01a7308 "bridge", 
    data=0x1464f06b2078 "{origination_uuid=419e285b-1d45-4309-977e-bc6655120c51,origination_caller_id_number=+867566351362,callout execute_on_ring='lua status.lua callout 07566351362 013560820253 +867566351362 013560820253 ri"...)
    at src/switch_cpp.cpp:777
#12 0x0000146a5890ad21 in _wrap_CoreSession_execute (L=0x1464f0061b40) at mod_lua_wrap.cpp:7684
#13 0x0000146a586c8c75 in ?? () from /lib/x86_64-linux-gnu/liblua5.2.so.0
#14 0x0000146a586d4825 in ?? () from /lib/x86_64-linux-gnu/liblua5.2.so.0
#15 0x0000146a586c8f9e in ?? () from /lib/x86_64-linux-gnu/liblua5.2.so.0
#16 0x0000146a586c85cf in ?? () from /lib/x86_64-linux-gnu/liblua5.2.so.0
#17 0x0000146a586c9201 in ?? () from /lib/x86_64-linux-gnu/liblua5.2.so.0
#18 0x0000146a586c50a1 in lua_pcallk () from /lib/x86_64-linux-gnu/liblua5.2.so.0
#19 0x0000146a588fa428 in docall (L=0x1464f0061b40, narg=0, nresults=0, perror=0, fatal=1) at mod_lua.cpp:92
#20 0x0000146a588fa975 in lua_parse_and_execute (L=<optimized out>, input_code=<optimized out>, session=0x1461b0013ac8) at mod_lua.cpp:194
#21 0x0000146a588fb181 in lua_function (session=0x1461b0013ac8, data=<optimized out>) at mod_lua.cpp:483
#22 0x0000146a62b3c194 in switch_core_session_exec (session=0x1461b0013ac8, application_interface=0x55ed0c6ddda0, arg=0x146233b14510 "siptrunk_to_ims.lua") at src/switch_core_session.c:2891
#23 0x0000146a62b3b835 in switch_core_session_execute_application_get_flags (session=0x1461b0013ac8, app=0x146233b14508 "lua", arg=0x146233b14510 "siptrunk_to_ims.lua", flags=0x0) at src/switch_core_session.c:2756
#24 0x0000146a62b3e1b3 in switch_core_standard_on_execute (session=0x1461b0013ac8) at src/switch_core_state_machine.c:354
#25 0x0000146a62b3fd21 in switch_core_session_run (session=0x1461b0013ac8) at src/switch_core_state_machine.c:651
#26 0x0000146a62b37ddc in switch_core_session_thread (thread=0x1468b0169340, obj=0x1461b0013ac8) at src/switch_core_session.c:1709
#27 0x0000146a62b381cb in switch_core_session_thread_pool_worker (thread=0x1468b0169340, obj=0x1468b01691d0) at src/switch_core_session.c:1772
#28 0x0000146a62eb98ae in dummy_worker (opaque=0x1468b0169340) at threadproc/unix/thread.c:151
#29 0x0000146a62a2dfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#30 0x0000146a625e34cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95$8 = 0x1464f0087430 "v=0\r\no=ZhongTou 0454342303 0454342305 IN IP4 10.215.70.92\r\ns=ZhongTou\r\nc=IN IP4 10.215.70.92\r\nt=0 0\r\nm=audio 38692 RTP/AVP 18 8 0 4 101\r\na=rtpmap:18 G729/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:4 G723/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-16\r\n"
```

**Comment by burne-muz** [comment]
I have a similar problem. Does anyone have a good solution?
