### ISSUE TITLE
CRASH: FreeSWITCH version: 1.10.3-release+git~20200511T105455Z~129de34d84~64bit- while Conference <con_fname> hup all | conference <conf_name> play remote http file. 

### ISSUE THREAD

**Issue by bee-jarvis** [signalwire/freeswitch#659]
Hi Team,
We are  facing frequent Crashes  for the FS 1.10.3 on MOD_CONFERENCE.
As per earlier issues reported on #636 we have compiled code with **listener-hangup-race** branch but no luck still we are facing same.
As per the suggestion mentioned on the same issue configured with
**./configure --enable-address-sanitizer**  
Linked Issue: #533 

**Test Scenario**
1.We originated 500 calls with mod_event_socket application by following command:
originate {origination_uuid=XXXX-XXXX-XXXX-             XXXX,origination_caller_id_number=1234,ignore_early_media=true}sofia/gateway/loadgw/1 &socket('127.0.0.1:9092 async full')

2.  From **outbound**  Event_socket Application , we sent following instructions to FS.
sendmsg 
call-command: execute
execute-app-name: conference
execute-app-arg: loadTest

3. To disconnect all Conference members we user inbound EVENT_SOCKET application/fs_cli executed  **conference loadTest hup all** 
**Result:**
mostly 80%  times  Freeswitch Crashed.  Report attached.

[20200526T110917Z-bt.txt](https://github.com/signalwire/freeswitch/files/4681775/20200526T110917Z-bt.txt)

**TEST-SENARIO 2:**
We also found one more different crash issue with **conference play with http:// example.com/example.mp3  **  irrespective of Conference Size.
-Same  if we play with http_cache://  or local mp3 file, FS is not crashing.

**Comment by andywolk** [comment]
@bee-jarvis  `./configure --enable-address-sanitizer` does enable some additional ASAN output in `freeswitch.log`
Please attach the log.

**Comment by andywolk** [comment]
Also, please run your test without address sanitizer but under valgrind:
```
valgrind --log-file=~/valgrind.txt /usr/local/freeswitch/bin/freeswitch
```

**Comment by bee-jarvis** [comment]
Hi Andywolk,
we are unable to reproduce the issue by making more calls in valgrind mode due to high CPU consumption.

As you asked sharing Freeswitch.log here.
[freeswitch.log](https://github.com/signalwire/freeswitch/files/4682863/freeswitch.log)

**Comment by bee-jarvis** [comment]
HI Andywolk, 
let me know if any log is required from my end to investigate further.

**Comment by kamalesh-p** [comment]
Running sofia with address sanitizer causes this issue. please help.

> ==2051792==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7fd3a8fb03d0 at pc 0x7fd3a94a3a35 bp 0x7fd3a8fb0280 sp 0x7fd3a8fb0278
> READ of size 8 at 0x7fd3a8fb03d0 thread T14
> ==2051792==AddressSanitizer: while reporting a bug found another one. Ignoring.
>     #0 0x7fd3a94a3a34 in t_len sofia-sip/su_tag_inline.h:140
>     #1 0x7fd3a94a3a34 in tl_len /zoho/build/WH_DIR/Mar_23_2023/ZOHO_CONFERENCING/ZOHO_CONFERENCING_6168030/ZOHO_CONFERENCING_DBUILD/build/ZOHO_CONFERENCING/pkg/freeswitch/libs/sofia-sip/libsofia-sip-ua/su/su_taglist.c:250
>     #2 0x7fd3a94a3f7d in tl_adup /zoho/build/WH_DIR/Mar_23_2023/ZOHO_CONFERENCING/ZOHO_CONFERENCING_6168030/ZOHO_CONFERENCING_DBUILD/build/ZOHO_CONFERENCING/pkg/freeswitch/libs/sofia-sip/libsofia-sip-ua/su/su_taglist.c:315
>     #3 0x7fd3a939cbf4 in nua_create /zoho/build/WH_DIR/Mar_23_2023/ZOHO_CONFERENCING/ZOHO_CONFERENCING_6168030/ZOHO_CONFERENCING_DBUILD/build/ZOHO_CONFERENCING/pkg/freeswitch/libs/sofia-sip/libsofia-sip-ua/nua/nua.c:154
>     #4 0x7fd3a9250453 in sofia_profile_thread_run /zoho/build/WH_DIR/Mar_23_2023/ZOHO_CONFERENCING/ZOHO_CONFERENCING_6168030/ZOHO_CONFERENCING_DBUILD/build/ZOHO_CONFERENCING/pkg/freeswitch/src/mod/endpoints/mod_sofia/sofia.c:3220
>     #5 0x7fd3b31970e3 in zm_root_thread src/zcon_thread_handler.c:175
>     #6 0x7fd3b37f243b in dummy_worker threadproc/unix/thread.c:151
>     #7 0x7fd3b2cadea6 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7ea6)
>     #8 0x7fd3b2bcda2e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0xfca2e)
> 
> Address 0x7fd3a8fb03d0 is located in stack of thread T14 at offset 0 in frame
>     #0 0x7fd3a939c97f in nua_create /zoho/build/WH_DIR/Mar_23_2023/ZOHO_CONFERENCING/ZOHO_CONFERENCING_6168030/ZOHO_CONFERENCING_DBUILD/build/ZOHO_CONFERENCING/pkg/freeswitch/libs/sofia-sip/libsofia-sip-ua/nua/nua.c:135
> 
>   This frame has 1 object(s):
>     [32, 88) 'ta'
> HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
>       (longjmp and C++ exceptions *are* supported)
> Thread T14 created by T0 here:
>     #0 0x7fd3b3f7cf59 in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x30f59)
>     #1 0x7fd3b37f2a05 in apr_thread_create threadproc/unix/thread.c:194
>     #2 0x7fd3b3197c2e in zm_create_thread_new src/zcon_thread_handler.c:210
>     #3 0x7fd3a923e8fe in launch_sofia_profile_thread /zoho/build/WH_DIR/Mar_23_2023/ZOHO_CONFERENCING/ZOHO_CONFERENCING_6168030/ZOHO_CONFERENCING_DBUILD/build/ZOHO_CONFERENCING/pkg/freeswitch/src/mod/endpoints/mod_sofia/sofia.c:3590
>     #4 0x7fd3a9240b24 in config_sofia /zoho/build/WH_DIR/Mar_23_2023/ZOHO_CONFERENCING/ZOHO_CONFERENCING_6168030/ZOHO_CONFERENCING_DBUILD/build/ZOHO_CONFERENCING/pkg/freeswitch/src/mod/endpoints/mod_sofia/sofia.c:6212
>     #5 0x7fd3a9221faf in mod_sofia_load /zoho/build/WH_DIR/Mar_23_2023/ZOHO_CONFERENCING/ZOHO_CONFERENCING_6168030/ZOHO_CONFERENCING_DBUILD/build/ZOHO_CONFERENCING/pkg/freeswitch/src/mod/endpoints/mod_sofia/mod_sofia.c:6186
>     #6 0x7fd3b2fd65c6 in switch_loadable_module_load_file src/switch_loadable_module.c:1494
>     #7 0x7fd3b2fd65c6 in switch_loadable_module_load_module_ex src/switch_loadable_module.c:1602
>     #8 0x7fd3b2fdc64a in switch_loadable_module_init src/switch_loadable_module.c:1912
>     #9 0x7fd3b2f1609a in switch_core_init_and_modload src/switch_core.c:2437
>     #10 0x55f50424e178 in main src/switch.c:1181
>     #11 0x7fd3b2af4d09 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x23d09)
> 
> SUMMARY: AddressSanitizer: stack-buffer-underflow sofia-sip/su_tag_inline.h:140 in t_len
> Shadow bytes around the buggy address:
>   0x0ffaf51ee020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   0x0ffaf51ee030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   0x0ffaf51ee040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   0x0ffaf51ee050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
>   0x0ffaf51ee060: f1 f1 00 f4 f4 f4 00 00 00 00 00 00 00 00 00 00
> =>0x0ffaf51ee070: 00 00 00 00 00 00 00 00 00 00[f1]f1 f1 f1 00 00
>   0x0ffaf51ee080: 00 00 00 00 00 f4 00 00 00 00 00 00 00 00 00 00
>   0x0ffaf51ee090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   0x0ffaf51ee0a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   0x0ffaf51ee0b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>   0x0ffaf51ee0c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> Shadow byte legend (one shadow byte represents 8 application bytes):
>   Addressable:           00
>   Partially addressable: 01 02 03 04 05 06 07
>   Heap left redzone:       fa
>   Heap right redzone:      fb
>   Freed heap region:       fd
>   Stack left redzone:      f1
>   Stack mid redzone:       f2
>   Stack right redzone:     f3
>   Stack partial redzone:   f4
>   Stack after return:      f5
>   Stack use after scope:   f8
>   Global redzone:          f9
>   Global init order:       f6
>   Poisoned by user:        f7
>   Container overflow:      fc
>   Array cookie:            ac
>   Intra object redzone:    bb
>   ASan internal:           fe
>   Left alloca redzone:     ca
>   Right alloca redzone:    cb
> ==2051792==ABORTING
>
