### ISSUE TITLE
[core] resampling segfault (segfault)

### ISSUE THREAD

**Issue by cdosoftei** [signalwire/freeswitch#74]
In some situations, FreeSWITCH will experience a segmentation fault when resampling is required in order to accommodate a different number of channels.

The issue can be recreated as follows:

* Stock 1.10-1 installation on Debian 10
* Launch FreeSWITCH with the vanilla configuration
* Using the default configured users, register with `1000` and dial the sample echo dialplan `9195`
* Initiate a recording via `uuid_record <uuid> start /tmp/test.raw`
* FreeSWITCH experiences a buffer overrun (output when compiled against the address sanitizer):
```
> uuid_record ddccf668-2354-41b2-8701-e9488006818a start /tmp/test.raw
[New Thread 0x7f9b1b9b9700 (LWP 19831)]
2019-10-24 23:30:49.687752 [DEBUG] switch_ivr_async.c:1347 Record session sample rate: 8000 -> 8000
2019-10-24 23:30:49.687752 [DEBUG] switch_core_media_bug.c:970 Attaching BUG to sofia/internal/1000@10.0.0.101

+OK Success

freeswitch@localhost> 2019-10-24 23:30:49.687752 [DEBUG] switch_ivr_async.c:1636 No silence detection configured; assuming start of speech
2019-10-24 23:30:49.727747 [DEBUG] switch_core_io.c:448 Setting BUG Codec PCMU:0
=================================================================
==19789==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x621000850900 at pc 0x7f9b35f8a240 bp 0x7f9b1b9b88b0 sp 0x7f9b1b9b88a8
WRITE of size 2 at 0x621000850900 thread T39
    #0 0x7f9b35f8a23f in switch_mux_channels src/switch_resample.c:317
    #1 0x7f9b35e65828 in switch_core_file_write src/switch_core_file.c:603
    #2 0x7f9b36006c14 in recording_thread src/switch_ivr_async.c:1281
    #3 0x7f9b362e4f8b in dummy_worker threadproc/unix/thread.c:151
    #4 0x7f9b35ca5fa2 in start_thread /build/glibc-vjB4T1/glibc-2.28/nptl/pthread_create.c:486
    #5 0x7f9b3585e4ce in clone (/lib/x86_64-linux-gnu/libc.so.6+0xf94ce)

0x621000850900 is located 0 bytes to the right of 4096-byte region [0x62100084f900,0x621000850900)
allocated by thread T39 here:
    #0 0x7f9b36996720 in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:105
    #1 0x7f9b35e656e4 in switch_core_file_write src/switch_core_file.c:595
    #2 0x7f9b36006c14 in recording_thread src/switch_ivr_async.c:1281
    #3 0x7f9b362e4f8b in dummy_worker threadproc/unix/thread.c:151

Thread T39 created by T35 here:
    #0 0x7f9b368fddb0 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cc:202
    #1 0x7f9b362e5171 in apr_thread_create threadproc/unix/thread.c:194

Thread T35 created by T0 here:
    #0 0x7f9b368fddb0 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cc:202
    #1 0x7f9b362e5171 in apr_thread_create threadproc/unix/thread.c:194

SUMMARY: AddressSanitizer: heap-buffer-overflow src/switch_resample.c:317 in switch_mux_channels
Shadow bytes around the buggy address:
  0x0c42801020d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42801020e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c42801020f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280102100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280102110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c4280102120:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280102130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280102140: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280102150: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280102160: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280102170: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==19789==ABORTING
[Thread 0x7f9b1b9b9700 (LWP 19831) exited]
[Thread 0x7f9b1baa9700 (LWP 19830) exited]
[Thread 0x7f9b1c974700 (LWP 19827) exited]
[Thread 0x7f9b1c9c7700 (LWP 19826) exited]
[Thread 0x7f9b1ca1a700 (LWP 19825) exited]
[Thread 0x7f9b1ca6d700 (LWP 19824) exited]
[Thread 0x7f9b1cd98700 (LWP 19823) exited]
[Thread 0x7f9b1cdeb700 (LWP 19822) exited]
[Thread 0x7f9b1ce30700 (LWP 19821) exited]
[Thread 0x7f9b263bc700 (LWP 19815) exited]
[Thread 0x7f9b26fc7700 (LWP 19814) exited]
[Thread 0x7f9b2702a700 (LWP 19813) exited]
[Thread 0x7f9b272e2700 (LWP 19812) exited]
[Thread 0x7f9b2753c700 (LWP 19811) exited]
[Thread 0x7f9b2e486700 (LWP 19810) exited]
[Thread 0x7f9b2e5b3700 (LWP 19809) exited]
[Thread 0x7f9b2e606700 (LWP 19808) exited]
[Thread 0x7f9b2e849700 (LWP 19807) exited]
[Thread 0x7f9b2e89c700 (LWP 19806) exited]
[Thread 0x7f9b2f179700 (LWP 19805) exited]
[Thread 0x7f9b304ad700 (LWP 19804) exited]
[Thread 0x7f9b2f31c700 (LWP 19803) exited]
[Thread 0x7f9b2f36f700 (LWP 19802) exited]
[Thread 0x7f9b2f3b4700 (LWP 19801) exited]
[Thread 0x7f9b2f8d7700 (LWP 19800) exited]
[Thread 0x7f9b2f91c700 (LWP 19799) exited]
[Thread 0x7f9b30cd4700 (LWP 19797) exited]
[Thread 0x7f9b30efc700 (LWP 19796) exited]
[Thread 0x7f9b311ff700 (LWP 19794) exited]
[Thread 0x7f9b31847700 (LWP 19793) exited]
[Thread 0x7f9b33c49a40 (LWP 19789) exited]
[Inferior 1 (process 19789) exited with code 01]
```

The trace is on point as the `data` buffer in the code below will be overrun when demuxing:

https://github.com/signalwire/freeswitch/blob/31d667670649775fc251752d81e2378951a0dc1f/src/switch_resample.c#L314-L318

As a side note, you may wonder how I ended up with more than one channel for a simple `PCMU@8000h@20i@1c` test call; the additional channel can be traced back to the `RECORD_STEREO` channel variable (which is explicitly set to true in the vanilla configuration):

https://github.com/signalwire/freeswitch/blob/15ad4c23e259c1c2dff58f89e9124e5f36dd2e94/src/switch_ivr_async.c#L2702-L2706

```
freeswitch@localhost> uuid_getvar ddccf668-2354-41b2-8701-e9488006818a record_stereo

true
```

I am happy to provide a PR but I'd like some direction from a senior core developer before proceeding. Here are a number of thoughts:

* Before invoking `switch_mux_channels`, ensure the buffer is large enough to accommodate the channel count (not just the original), i.e. change `need` so it accounts for the largest channel count (`int need = *len * 2 * (fh->real_channels >= fh->channels ? fh->real_channels : fh->channels)`)

https://github.com/signalwire/freeswitch/blob/31d667670649775fc251752d81e2378951a0dc1f/src/switch_core_file.c#L591-L604

* @anthmFS has originally proposed an alternative approach which does account for the correct buffer size (however, the sample population _appears_ a bit different that the current implementation):

https://github.com/signalwire/freeswitch/blob/31d667670649775fc251752d81e2378951a0dc1f/src/switch_resample.c#L326-L340

* Also, perhaps `RECORD_STEREO` alone (at least in contexts similar to this one) should not trigger channel demuxing at all

* Other ideas :-)

**Comment by dragos-oancea** [comment]
can you try this patch: https://github.com/signalwire/freeswitch/pull/78 ?

**Comment by cdosoftei** [comment]
The patch is definitely effective as far as reported segfault is concerned. I dropped a quick note on the PR though.
