### ISSUE TITLE
failed to detect STUN address -> daemon crush

### ISSUE THREAD

**Issue by sergey-safarov** [signalwire/freeswitch#916]
**Describe the bug**
From time to time current master and vanilla config cannot detect STUN address.
```
(gdb) 
(gdb) 
(gdb) r
Starting program: /usr/local/freeswitch/bin/freeswitch -nonat
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
ERROR: Could not set nice level
[New Thread 0x7ffff62fc700 (LWP 230883)]
2020-10-18 10:59:42.135826 [INFO] switch_event.c:710 Activate Eventing Engine.
[New Thread 0x7ffff61be700 (LWP 230884)]
2020-10-18 10:59:42.146204 [WARNING] switch_event.c:680 Create additional event dispatch thread 0

2020-10-18 10:59:47.176921 [ERR] switch_stun.c:900 STUN Failed! [Timeout]
2020-10-18 10:59:47.176997 [ERR] switch_xml.c:175 stun-set failed.





2020-10-18 10:59:52.199049 [ERR] switch_stun.c:900 STUN Failed! [Timeout]
2020-10-18 10:59:52.199126 [ERR] switch_xml.c:175 stun-set failed.
[New Thread 0x7ffff60ca700 (LWP 230885)]
[New Thread 0x7ffff5fc8700 (LWP 230886)]
[New Thread 0x7ffff5da1700 (LWP 230887)]
2020-10-18 10:59:52.270606 [DEBUG] switch_scheduler.c:252 Added task 1 heartbeat (core) to run at 1603018792
2020-10-18 10:59:52.270628 [DEBUG] switch_scheduler.c:252 Added task 2 check_ip (core) to run at 1603018792
2020-10-18 10:59:52.270847 [NOTICE] switch_core.c:1467 Created ip list rfc6598.auto default (deny)
2020-10-18 10:59:52.270859 [NOTICE] switch_utils.c:658 Adding 100.64.0.0/10 (allow) [] to list rfc6598.auto
2020-10-18 10:59:52.270865 [NOTICE] switch_core.c:1473 Created ip list rfc1918.auto default (deny)
2020-10-18 10:59:52.270871 [NOTICE] switch_utils.c:658 Adding 10.0.0.0/8 (allow) [] to list rfc1918.auto
2020-10-18 10:59:52.270876 [NOTICE] switch_utils.c:658 Adding 172.16.0.0/12 (allow) [] to list rfc1918.auto
2020-10-18 10:59:52.270881 [NOTICE] switch_utils.c:658 Adding 192.168.0.0/16 (allow) [] to list rfc1918.auto
```
In log above string "**switch_stun.c:897 External ip address detected using STUN**" does not exist.
And then when started `external` and `internal` profiles FS crushed
```
2020-10-18 10:59:52.323252 [NOTICE] switch_loadable_module.c:412 Adding API Function 'event_sink'
2020-10-18 10:59:52.345116 [INFO] mod_sofia.c:6247 Starting initial message thread.
2020-10-18 10:59:52.345259 [WARNING] sofia.c:5228 rtp-timeout-sec deprecated use media_timeout variable.
2020-10-18 10:59:52.345263 [WARNING] sofia.c:5235 rtp-hold-timeout-sec deprecated use media_hold_timeout variable.
2020-10-18 10:59:52.345308 [INFO] sofia.c:6029 Setting MAX Auth Validity to 0 Attempts
[New Thread 0x7ffff47ec700 (LWP 230891)]
2020-10-18 10:59:52.345594 [NOTICE] sofia.c:6196 Started Profile external-ipv6 [sofia_reg_external-ipv6]
2020-10-18 10:59:52.345685 [ERR] sofia.c:5084 Invalid ext-rtp-ip
2020-10-18 10:59:52.345688 [ERR] sofia.c:5181 Invalid ext-sip-ip
2020-10-18 10:59:52.345692 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::notify_refer
2020-10-18 10:59:52.345695 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::notify_watched_header
2020-10-18 10:59:52.345697 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::unregister
2020-10-18 10:59:52.345699 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::profile_start
2020-10-18 10:59:52.345701 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::reinvite
2020-10-18 10:59:52.345708 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::replaced
2020-10-18 10:59:52.345710 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::transferor
2020-10-18 10:59:52.345711 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::transferee
2020-10-18 10:59:52.345713 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::error
2020-10-18 10:59:52.345715 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::intercepted
2020-10-18 10:59:52.345717 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::gateway_state
2020-10-18 10:59:52.345718 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::sip_user_state
2020-10-18 10:59:52.345720 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::gateway_delete
2020-10-18 10:59:52.345722 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::expire
2020-10-18 10:59:52.345724 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::register_attempt
2020-10-18 10:59:52.345726 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::register_failure
2020-10-18 10:59:52.345727 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::pre_register
2020-10-18 10:59:52.345729 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::register
2020-10-18 10:59:52.345731 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::gateway_add
2020-10-18 10:59:52.345732 [NOTICE] switch_event.c:464 Subclass reservation deleted for mod_sofia.c:sofia::bye_response
2020-10-18 10:59:52.347264 [CRIT] switch_loadable_module.c:1785 Error Loading module /usr/local/freeswitch/mod/mod_sofia.so
**Module load routine returned an error**

Thread 10 "freeswitch" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff47ec700 (LWP 230891)]
0x00007ffff48eeeb8 in ?? ()
```

**To Reproduce**
1. Using this vanila configuration...
2. Start freeswitch multiple times
3. in about 25% freeswitch dies.

**Expected behavior**
Add to log a description of the required external IPv4 address.
Add to log a description of how to set a custom STUN server.

**Package version or git hash**
commit 1010c6c55c35b9df738c67bc80cb353c873dab76

**Trace logs**
not captured

**backtrace from core file**
If applicable, provide the full backtrace from the core file.
```
(gdb) bt
#0  0x00007ffff48eeeb8 in ?? ()
#1  0x00007ffff7d10bd6 in dummy_worker (opaque=0x747960) at threadproc/unix/thread.c:151
#2  0x00007ffff72355a2 in start_thread () from /lib64/libpthread.so.0
#3  0x00007ffff6dec023 in clone () from /lib64/libc.so.6
(gdb) 
```

**Comment by oanguenot** [comment]
Hi, same issue on my side using v1.10 branch on MacOS.

It was working well 2 days ago and today, I tried to restart freeswitch and had that issue.

Is it related to mod sofia-sip ?

Thanks in advance

**Comment by chengxiang621** [comment]
Hi, same issue on my side using v1.10 branch on CentOS7.

It was working well 2 days ago and today, I tried to restart freeswitch and had that issue.

problem phenomenon ：
2020-10-30 15:00:56.675569 [ERR] switch_stun.c:900 STUN Failed! [Timeout]
2020-10-30 15:00:56.675620 [ERR] switch_xml.c:175 stun-set failed.
2020-10-30 14:58:16.271784 [ERR] mod_signalwire.c:302 SignalWire adoption failed: stun [stun.freeswitch.org] lookup error: Timeout

Thanks in advance

**Comment by chetansonawane03** [comment]
i have also got same issue after restart freeswitch service on centos 7. Please advice, how I can ressolve this issue 

below are the logs trigger 
2020-10-31 05:27:45.649476 [DEBUG] sofia.c:4628 ext-rtp-ip []
2020-10-31 05:27:45.649486 [ERR] sofia.c:5083 Invalid ext-rtp-ip
2020-10-31 05:27:45.649495 [DEBUG] sofia.c:4628 ext-sip-ip []
2020-10-31 05:27:45.649503 [ERR] sofia.c:5180 Invalid ext-sip-ip

**Comment by hawkdavis** [comment]
this is really annoying i'm having the same issue.

**Comment by briankwest** [comment]
just set the address for now, an empty string will crash, their is a fix for this coming.

**Comment by oanguenot** [comment]
Thanks Brian

**Comment by wangqingwen** [comment]
> just set the address for now, an empty string will crash, their is a fix for this coming.

i have also got the same issue,which version will be fixed?
thanks for your answer!
