### ISSUE TITLE
Freeswitch crash

### ISSUE THREAD

**Issue by ericfallstrom** [signalwire/freeswitch#932]
Freeswitch occasionally crashes. We are not doing anything out of the ordinary when the crash happens. We had approximately 100 sip registrations (via WebRTC) and ~100 active calls. 

Freeswitch was installed using the recommended instructions for Centos 7 (RPM Packages)

Versions:
```
CentOS Linux release 7.8.2003 (Core)
FreeSWITCH version: 1.10.5-release.8~64bit (-release.8 64bit)
```

From system logs:
```
Oct 28 10:47:52 freeswitch: freeswitch: nta.c:8107: outgoing_create: Assertion `orq->orq_queue' failed.
Oct 28 10:47:52 abrt-hook-ccpp: Process 11669 (freeswitch) of user 0 killed by SIGABRT - dumping core
```

(gdb) bt:
```
#0  0x00007fa8ead0b387 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007fa8ead0ca78 in __GI_abort () at abort.c:90
#2  0x00007fa8ead041a6 in __assert_fail_base (fmt=0x7fa8eae5fce0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fa8ec318714 "orq->orq_queue", file=file@entry=0x7fa8ec317e21 "nta.c", line=line@entry=8107, function=function@entry=0x7fa8ec31a9e0 <__PRETTY_FUNCTION__.17997> "outgoing_create") at assert.c:92
#3  0x00007fa8ead04252 in __GI___assert_fail (assertion=assertion@entry=0x7fa8ec318714 "orq->orq_queue", file=file@entry=0x7fa8ec317e21 "nta.c", line=line@entry=8107, function=function@entry=0x7fa8ec31a9e0 <__PRETTY_FUNCTION__.17997> "outgoing_create") at assert.c:101
#4  0x00007fa8ec276af8 in outgoing_create (agent=<optimized out>, callback=<optimized out>, magic=<optimized out>, route_url=0x7fa80003ff00, tpn=<optimized out>, msg=<optimized out>, tag=0x7fa8ec556c60 <ntatag_default_proxy>, value=140359531495168) at nta.c:8107
#5  0x00007fa8ec277aad in nta_outgoing_mcreate (agent=0x7fa800001e40, callback=callback@entry=0x7fa8ec293c20 <nua_client_orq_response>, magic=0x7fa800125b50, route_url=route_url@entry=0x0, msg=msg@entry=0x7fa8001267a0, tag=tag@entry=0x7fa8ec556c60 <ntatag_default_proxy>, value=value@entry=140359531495168) at nta.c:7491
#6  0x00007fa8ec293da8 in nua_base_client_request (cr=cr@entry=0x7fa800125b50, msg=0x7fa8001267a0, sip=<optimized out>, tags=tags@entry=0x7fa80bffea00) at nua_client.c:960
#7  0x00007fa8ec294e52 in nua_base_client_trequest (cr=0x7fa800125b50, msg=<optimized out>, sip=<optimized out>, tag=<optimized out>, value=<optimized out>) at nua_client.c:928
#8  0x00007fa8ec2a2bc3 in nua_bye_client_request (cr=<optimized out>, msg=<optimized out>, sip=<optimized out>, tags=<optimized out>) at nua_session.c:3816
#9  0x00007fa8ec29406a in nua_client_request_sendmsg (cr=cr@entry=0x7fa800125b50) at nua_client.c:903
#10 0x00007fa8ec294ef9 in nua_client_request_try (cr=0x7fa800125b50) at nua_client.c:710
#11 0x00007fa8ec292d03 in nua_client_init_request0 (cr=0x7fa800125b50) at nua_client.c:607
#12 nua_client_init_request (cr=0x7fa800125b50) at nua_client.c:444
#13 0x00007fa8ec2933e6 in nua_client_create (nh=<optimized out>, event=<optimized out>, methods=<optimized out>, tags=<optimized out>) at nua_client.c:201
#14 0x00007fa8ec28fe63 in nua_stack_signal (nua=0x7fa8040012b0, msg=<optimized out>, ee=0x7fa65010e018) at nua_stack.c:607
#15 0x00007fa8ec2e1042 in su_base_port_execute_msgs (queue=0x0) at su_base_port.c:280
#16 0x00007fa8ec2e15cd in su_base_port_run (self=0x7fa8000008c0) at su_base_port.c:335
#17 0x00007fa8ec2e1ce0 in su_pthread_port_clone_main (varg=0x7fa868568650) at su_pthread_port.c:343
#18 0x00007fa8eb77fea5 in start_thread (arg=0x7fa80bfff700) at pthread_create.c:307
#19 0x00007fa8eadd38dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by andywolk** [comment]
Do you have IPv6 setup?

**Comment by ericfallstrom** [comment]
We are listening only on IPv4 addresses. We are not using the internal-ipv6 or external-ipv6 profiles.

**Comment by andywolk** [comment]
Do you have an IPv6 address on the box?

**Comment by ericfallstrom** [comment]
Yes. The interface we use for WebRTC has both a IPv4 and IPv6 address. We are only listening and connecting to the IPv4 address.

**Comment by andywolk** [comment]
Duplicate https://github.com/signalwire/freeswitch/issues/814

**Comment by andywolk** [comment]
I believe it's fixed. See https://github.com/freeswitch/sofia-sip/pull/123
Reopen if the issue exists still.
